### ISSUE TITLE
chatButton new icon does not get cropped properly

### ISSUE THREAD

**Issue by saitnyalcin** [tjtanjin/react-chatbotify#101]
**Bug Description**
after upgrading to version 1.7.0 to "react-chatbotify": "^2.0.0-beta.5", in my react app, my custom chatButton does not get cropped properly to show better looking. It shows the corners and does not replace the whole chatButton image. Please be advised

**Steps To Reproduce**
Steps to reproduce the bug behavior:
1. implement the following code in the chatbot

```
import customImage from "./assets/customImage .jpg";

  return (
    <ChatBot
      settings={{
        chatButton: { icon: customImage },
      }}
      styles={{
      }}
      flow={flow}
    />
  );

```
3. run the app
4. and you will see that the new custom image is not cropped properly after upgrading to the latest version

**Expected behavior**
supposed to cover the whole background image of the chatbutton

**Screenshots**
![Screenshot 2024-08-22 132634](https://github.com/user-attachments/assets/dce439d6-e786-486c-b70a-a1839928d003)

 - OS: Windows
 - Browser: chrome

**Comment by saitnyalcin** [comment]
@tjtanjin What I think is if we can add `border-radius: inherit ` style to the "rcb-toggle-icon" as mentioned below and can be seen in the screenshot as well, the issue will be resolved, please let me know what do you think

<span class="rcb-toggle-icon" style="background-image: url(&quot;/src/assets/customeImage.jpg&quot;);border-radius: inherit;"></span>

![Screenshot 2024-08-22 141602](https://github.com/user-attachments/assets/ae336725-fceb-4823-b81c-e41b632697be)

**Comment by saitnyalcin** [comment]
![Screenshot 2024-08-22 142509](https://github.com/user-attachments/assets/924a08a7-c1b0-4019-bd37-5783d47d16af)

**Comment by tjtanjin** [comment]
Hey @saitnyalcin, thank you for raising this up. Your proposed solution works, and I can work on a possible patch tomorrow along with some other fixes. The earliest I'll work on this is tomorrow, so feel free to open a PR for this fix if you'd like 😛

**Comment by tjtanjin** [comment]
Thank you for the PR 😄
