### ISSUE TITLE
[Task] Add typing indicator inline style

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#105]
**Description:**
There is currently no style section for modifying typing indicators. Users have to target the CSS classes directly. That's not great, and it would be nice to have inline styles for typing indicator as described in #91

**Comment by damirgros** [comment]
Hello, could I take on this issue? We talked on discord the other day ( name: dgmanisch ).

**Comment by tjtanjin** [comment]
> Hello, could I take on this issue? We talked on discord the other day ( name: dgmanisch ).

Sure thing! 😊

**Comment by tjtanjin** [comment]
Resolved by #107
