### ISSUE TITLE
[Feat] Blog

### ISSUE THREAD

**Issue by Bashamega** [tjtanjin/react-chatbotify#106]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. (e.g. I'm always frustrated when [...])

Create a blog for the bot

**Describe the solution you'd like**

Create a simple CMS platform for the website

**Describe alternatives you've considered**
NONE

**Additional context**
I would like to work on this

**Comment by tjtanjin** [comment]
Hey @Bashamega! A little unsure of the relevance to the core library, can you elaborate more on this blog/cms feature?

**Comment by Bashamega** [comment]
> Hey @Bashamega! A little unsure of the relevance to the core library, can you elaborate more on this blog/cms feature?

I have replied to you on discord
