### ISSUE TITLE
[Feat]Disable Enter key events during IME conversion in ChatInput

### ISSUE THREAD

**Issue by daichi000** [tjtanjin/react-chatbotify#109]
**Is your feature request related to a problem? Please describe.**
The problem occurs in the ChatInput component. Currently, when the Enter key is pressed while text is undergoing IME (Input Method Editor) conversion, it triggers form submission events. This can lead to incomplete or unintended input submissions, which is particularly frustrating when composing messages in languages that require conversion, like Japanese.

**Describe the solution you'd like**
I want to add an isComposing state to the ChatInput component to prevent events from being triggered when the Enter key is pressed during IME conversion

**Describe alternatives you've considered**

**Additional context**

https://github.com/user-attachments/assets/f0c352d8-0fbe-4f7c-be09-79a8de419b97

**Comment by daichi000** [comment]
@tjtanjin Hi! can I work on this issue?

**Comment by tjtanjin** [comment]
> @tjtanjin Hi! can I work on this issue?

Hey, thank you for raising and taking up this issue! Can I suggest you wait another 1-2 days before starting? There is an ongoing major refactor which I had hoped to put out over the weekends but I fell sick 😢 I'll be able to get the changes out in 1-2 days so it'll be better for you to work on it then - otherwise with the scale of the refactor, there'll very likely be conflicts.

**Comment by daichi000** [comment]
Thank you for your response. I'll follow your suggestion and wait for 1-2 days before starting my work. Please take care!

**Comment by tjtanjin** [comment]
Hey @daichi000, you may pull the latest changes from the `main` branch now and try to address this issue. Thank you for your patience! 😊

P.S: In case you have a change of plans, do let me know if you're no longer working on the issue so that I can open it up!
