### ISSUE TITLE
[Task] Add integration test cases showing and dismissing of toasts

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#110]
**Task Description:**
Currently, we run a suite of integration tests using cypress which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/cypress).

However, the test cases do not cover the showing/dismissing of toasts via `params.showToast` and `params.dismissToast`.

**Deliverables:**
New integration test cases that cover the testing of showing/dismissing of toasts.

**Additional Context:**
Note that this will require modifications to `flow` within `App.tsx` which currently does not use toast.

**Comment by AmTryingMyBest** [comment]
@tjtanjin I'd like to take this up. Assign me it? :)

**Comment by tjtanjin** [comment]
Go for it!

**Comment by tjtanjin** [comment]
Hi @AmTryingMyBest! Checking in to see if you're facing any problems working on the issue. Feel free to reach out!

**Comment by tjtanjin** [comment]
Hey @AmTryingMyBest! With hacktoberfest drawing closer to the end, I'll be re-opening this issue for others that may be keen in this final stretch. That said, if you're still interested, feel free to open a PR soonest!
