### ISSUE TITLE
[Task] Add integration test cases for markup language

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#125]
**Task Description:**
Currently, we run a suite of integration tests using cypress which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/cypress).

However, the test cases do not cover the [markup language](https://react-chatbotify.com/docs/api/settings#botbubble) feature which is set via `dangerouslySetInnerHtml` within the `userBubble` and `botBubble` sections.

**Deliverable(s):**
New integration test cases that cover the testing of markup language.

**Additional Context:**
A possible approach is to have markup language disabled by default, then check that attempts to send `<b>hello</b>` or similar texts should result in an unformatted plain text string.

**Comment by tasbi03** [comment]
Hey can you assign this to me ?

**Comment by tjtanjin** [comment]
> Hey can you assign this to me ? 

Hey @tasbi03! Sorry for the confusion, this test case was added in a previous PR but I've overlooked to close it 🥹 I'll be closing this issue now, but feel free to pick up other unassigned ones!
