### ISSUE TITLE
[Task] Add unit test cases for useMessagesInternal hook

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#126]
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `useMessagesInternal` hook.

**Deliverable(s):**
New unit test cases that cover the testing of the `useMessagesInternal` hook.

**Additional Context:**
- Hooks API can be found [**here**](https://react-chatbotify.com/docs/api/hooks)
- Existing unit test for hooks can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__/hooks) which may serve as a good source for reference.

**Comment by Goketech** [comment]
I opened a pull request for this issue, [pr 234](https://github.com/tjtanjin/react-chatbotify/pull/234)
