### ISSUE TITLE
[Task] Add unit test cases for usePathsInternal hook

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#127]
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `usePathsInternal` hook.

**Deliverable(s):**
New unit test cases that cover the testing of the `usePathsInternal` hook.

**Additional Context:**
- Hooks API can be found [**here**](https://react-chatbotify.com/docs/api/hooks)
- Existing unit test for hooks can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__/hooks) which may serve as a good source for reference.

**Comment by xenom2004** [comment]
hi @tjtanjin I would like to contribute in this, can you plz assign this to me

**Comment by tjtanjin** [comment]
Go for it!

**Comment by tjtanjin** [comment]
Hey @xenom2004! With hacktoberfest drawing closer to the end, I'll be re-opening this issue for others that may be keen in this final stretch. That said, if you're still interested, feel free to open a PR soonest!

**Comment by anjumnnit** [comment]
Hey can you assign this to me? plz I tried this and almost done with it will raise the PR just after you assign this. @tjtanjin

**Comment by tjtanjin** [comment]
> Hey can you assign this to me? plz I tried this and almost done with it will raise the PR just after you assign this. @tjtanjin

Go for it!

**Comment by anjumnnit** [comment]
> > Hey can you assign this to me? plz I tried this and almost done with it will raise the PR just after you assign this. @tjtanjin
> 
> Go for it!

you can review it plzz I still have PR's to raise.
