### ISSUE TITLE
[Help] How to support new lines in message content

### ISSUE THREAD

**Issue by ahetawal-p** [tjtanjin/react-chatbotify#13]
Hello,
My api returns some content which is formatted with new lines and some lists. Something like this:

```
Details for the product:
 - A 
 - B
 - C
Another detail:
 - X
 - Y
 ```
How can I suppose this in the message rendering when a bot responds ?

**Comment by tjtanjin** [comment]
Hi @ahetawal-p, there's 2 approaches to this:

1) Use `params.injectMessage` multiple times to send each detail as a different message and hence distinguishing between lines.
2) Use the `render` attribute to include your own custom react component - which means you can write a component that handles parsing/formatting however you wish.

**Comment by tjtanjin** [comment]
@ahetawal-p The [render component](https://react-chatbotify.tjtanjin.com/docs/examples/render_component) example gives you an idea of how it can be done. See if it's helpful for you.

**Comment by ahetawal-p** [comment]
@tjtanjin i did look at it, i guess my question is how do i pass the response from 
```
const data = await makeApiCall('allIncidents')
        return data
```
To pass to render function so it can render the data with the `<pre></pre>` tags...

**Comment by tjtanjin** [comment]
@ahetawal-p You can refer to the [table listing the attributes](https://react-chatbotify.tjtanjin.com/docs/api/attributes). For your case, since `render` takes in a function as well, you would make your API call within the `render` attribute rather than within `message`. That way there's no need to consider passing information.

**Comment by tjtanjin** [comment]
Hey @ahetawal-p! May I assume this is resolved?

**Comment by ahetawal-p** [comment]
Yes, thank you
