### ISSUE TITLE
[Task] Add unit test cases for useToastsInternal hook

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#130]
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `useToastsInternal` hook.

**Deliverable(s):**
New unit test cases that cover the testing of the `useToastsInternal` hook.

**Additional Context:**
- Hooks API can be found [**here**](https://react-chatbotify.com/docs/api/hooks)
- Existing unit test for hooks can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__/hooks) which may serve as a good source for reference.

**Comment by tjtanjin** [comment]
> I want to give it a try to this one.

Go for it!

**Comment by tjtanjin** [comment]
Hey @manoshatzi! Checking in to see if you're facing any problems working on the issue. Feel free to reach out!

**Comment by tjtanjin** [comment]
Hey @manoshatzi! With hacktoberfest drawing closer to the end, I'll be re-opening this issue for others that may be keen in this final stretch. That said, if you're still interested, feel free to open a PR soonest!

**Comment by manoshatzi** [comment]
Hey @tjtanjin. Yes do that. So sorry for not have been finish it but I was really too busy and my spare time was really too less.

**Comment by anjumnnit** [comment]
can you please assigned this me please I tried it already.  @tjtanjin

**Comment by Nandinibajaj16** [comment]
@tjtanjin can you assign this to me

**Comment by anjumnnit** [comment]
> can you please assign this me? I tried it already. @tjtanjin

Can you please assign this on the  basis of fcfs as I have only one PR left for hackotberfest'24 :)...

**Comment by tjtanjin** [comment]
Hey @anjumnnit, I'll assign this issue to you since you requested for it first. I'll keep the PR from @Nandinibajaj16 open in the meantime, in case the issue is left incomplete.

Separately @Nandinibajaj16, I've tagged the PR from you with `hacktoberfest-accepted` so that your efforts are not wasted. However, as mentioned in the contributing guidelines, the issue should be assigned to you before working on it (FCFS, to avoid conflicts such as this). Hope to seek your understanding!

**Comment by Nandinibajaj16** [comment]
@tjtanjin My bad didn't see the updates on the issue before raising the PR, it's okay :)

**Comment by anjumnnit** [comment]
> Hey @anjumnnit, I'll assign this issue to you since you requested for it first. I'll keep the PR from @Nandinibajaj16 open in the meantime, in case the issue is left incomplete.
> 
> Separately @Nandinibajaj16, I've tagged the PR from you with `hacktoberfest-accepted` so that your efforts are not wasted. However, as mentioned in the contributing guidelines, the issue should be assigned to you before working on it (FCFS, to avoid conflicts such as this). Hope to seek your understanding!

tysm 😿
