### ISSUE TITLE
[Task] Add unit test cases for useSettingsInternal hook

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#131]
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `useSettingsInternal` hook.

**Deliverable(s):**
New unit test cases that cover the testing of the `useSettingsInternal` hook.

**Additional Context:**
- Hooks API can be found [**here**](https://react-chatbotify.com/docs/api/hooks)
- Existing unit test for hooks can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__/hooks) which may serve as a good source for reference.

**Comment by anandxs** [comment]
I could not find the `useSettingsInternal` hook in the project. From what I understand, the `useSettings` hook directly accesses the `settings` and `setSettings` context and returns them.

**Comment by tjtanjin** [comment]
> I could not find the `useSettingsInternal` hook in the project. From what I understand, the `useSettings` hook directly accesses the `settings` and `setSettings` context and returns them.

Hey @anandxs! Thank you for pointing it out and apologies for the confusion. You're right to observe that settings hook itself doesn't currently hold any internal logic. I'm contemplating adding a utility function to make updating of settings easier instead of having users directly deal with the setter. Let me ponder over this for a bit more - in the meantime, please feel free to look at other issues if you are keen 🥹

**Comment by tjtanjin** [comment]
Hey @anandxs, there's an internal hook for settings now. Let me know if you're still keen to work on it 😊

**Comment by anandxs** [comment]
Sure. I'd like to take it.
