### ISSUE TITLE
[Task] Add unit test cases for VoiceButton component

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#137]
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `VoiceButton` component.

**Deliverable(s):**
New unit test cases that cover the testing of the `VoiceButton` component.

**Additional Context:**
- Button components can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/src/components/Buttons)
- An example for `AudioButton` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/components/AudioButton.test.tsx) which may serve as a good source for reference

**Comment by jerry-604** [comment]
I'll like to work on this...

**Comment by tjtanjin** [comment]
> I'll like to work on this...

Go for it!

**Comment by tjtanjin** [comment]
Hey @jerry-604, are you facing any problems with this issue? If so, feel free to reach out for clarifications!

**Comment by tjtanjin** [comment]
Hey @jerry-604, with hacktoberfest coming to a close very soon, I'll be leaving this issue un-assigned for any final PRs. This is to minimize leftover issues and provide an opportunity for those looking to get that last few PRs in. Feel free to continue with a PR if you're still working on this issue and I seek your kind understanding, thank you! 😊

**Comment by Elisassa** [comment]
Hi! If there is no one working on this I would like to have a try!

**Comment by tjtanjin** [comment]
> Hi! If there is no one working on this I would like to have a try!

Go for it!

**Comment by Elisassa** [comment]
Hi I have made PR pls check if it's ok

**Comment by SDaniV** [comment]
Hey @tjtanjin! I found that the issue has been hanging unchanged for more than a month now so I decided to give it a try and created [alternative PR](https://github.com/tjtanjin/react-chatbotify/pull/287) to resolve it. Please, review when you have time. Thanks!
