### ISSUE TITLE
[Task] Add unit test cases for EmojiButton component

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#140]
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `EmojiButton` component.

**Deliverable(s):**
New unit test cases that cover the testing of the `EmojiButton` component.

**Additional Context:**
- Button components can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/src/components/Buttons)
- An example for `AudioButton` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/components/AudioButton.test.tsx) which may serve as a good source for reference

**Comment by heinthetaung-dev** [comment]
I will work on this.

**Comment by tjtanjin** [comment]
> I will work on this.

Go for it!

**Comment by tjtanjin** [comment]
Hey @heinthetaung-dev, a PR has just been opened for this issue: https://github.com/tjtanjin/react-chatbotify/pull/154

Given that you are first to indicate your interest for it and also assigned the issue, I think it's only fair to give you the priority in deciding. Here are 2 possible ways to proceed:

1) If you have not started and are willing to let the other developer have the issue, I can merge the current PR and explore other alternative issues with you.
2) If you have already started, I can reject the PR from the other developer (I can still mark the PR as `hacktoberfest-accepted`, which hopefully means the PR efforts are not wasted).

Let me know which option works out for you!

**Comment by heinthetaung-dev** [comment]
@tjtanjin no worries. Thanks for letting me know. I haven't started yet so you can merge the other PR.

**Comment by tjtanjin** [comment]
> @tjtanjin no worries. Thanks for letting me know. I haven't started yet so you can merge the other PR.

Thank you for your kind understanding 🥹 I'll be happy to help you explore other issues if you wish to (possibly via discord). Feel free to connect!

**Comment by heinthetaung-dev** [comment]
No problem. I will also take a look at other unit test issues.

**Comment by heinthetaung-dev** [comment]
> > @tjtanjin no worries. Thanks for letting me know. I haven't started yet so you can merge the other PR.
> 
> Thank you for your kind understanding 🥹 I'll be happy to help you explore other issues if you wish to (possibly via discord). Feel free to connect!


No problem. I will also take a look at other unit test issues.

**Comment by tjtanjin** [comment]
Hey @heinthetaung-dev, it's been 3 days since the PR was opened and I haven't been able to get a response. I usually tend to wait a longer period but seeing as this was originally your issue, I think it's reasonable to close the existing PR and return the issue to you. Let me know if you're still keen, or I can re-open this to others as well 😄

**Comment by heinthetaung-dev** [comment]
> Hey @heinthetaung-dev, it's been 3 days since the PR was opened and I haven't been able to get a response. I usually tend to wait a longer period but seeing as this was originally your issue, I think it's reasonable to close the existing PR and return the issue to you. Let me know if you're still keen, or I can re-open this to others as well 😄

@tjtanjin I'll be glad to work on this issue. 😄  Please assign this to me.

**Comment by tjtanjin** [comment]
> > Hey @heinthetaung-dev, it's been 3 days since the PR was opened and I haven't been able to get a response. I usually tend to wait a longer period but seeing as this was originally your issue, I think it's reasonable to close the existing PR and return the issue to you. Let me know if you're still keen, or I can re-open this to others as well 😄
> 
> @tjtanjin I'll be glad to work on this issue. 😄 Please assign this to me.

The assignment never left you 😝

**Comment by heinthetaung-dev** [comment]
> > > Hey @heinthetaung-dev, it's been 3 days since the PR was opened and I haven't been able to get a response. I usually tend to wait a longer period but seeing as this was originally your issue, I think it's reasonable to close the existing PR and return the issue to you. Let me know if you're still keen, or I can re-open this to others as well 😄
> 
> > 
> 
> > @tjtanjin I'll be glad to work on this issue. 😄 Please assign this to me.
> 
> 
> 
> The assignment never left you 😝 

I will work on it.
