### ISSUE TITLE
[Task] Add unit test cases for FileAttachmentButton component

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#141]
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `FileAttachmentButton` component.

**Deliverable(s):**
New unit test cases that cover the testing of the `FileAttachmentButton` component.

**Additional Context:**
- Button components can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/src/components/Buttons)
- An example for `AudioButton` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/components/AudioButton.test.tsx) which may serve as a good source for reference

**Comment by Sarveshk76** [comment]
Hi @tjtanjin , I would like to work on this issue

**Comment by tjtanjin** [comment]
Hey @Sarveshk76, are you facing problems with this issue? If so, feel free to reach out for clarifications!

**Comment by tjtanjin** [comment]
Hey @Sarveshk76, with hacktoberfest coming to a close very soon, I'll be leaving this issue un-assigned for any final PRs. This is to minimize leftover issues and provide an opportunity for those looking to get that last few PRs in. Feel free to continue with a PR if you're still working on this issue and I seek your kind understanding, thank you! 😊

**Comment by cleobnvntra** [comment]
Hi @tjtanjin ! Can you please assign this issue to me? I already have a PR ready for this issue, I will just wait for your confirmation!😊

**Comment by tjtanjin** [comment]
> Hi @tjtanjin ! Can you please assign this issue to me? I already have a PR ready for this issue, I will just wait for your confirmation!😊

Go for it!
