### ISSUE TITLE
[Task] Add unit test cases for ChatBotButton component

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#145]
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `ChatBotButton` component.

**Deliverable(s):**
New unit test cases that cover the testing of the `ChatBotButton` component.

**Additional Context:**
- The `ChatBotButton` components can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/src/components/ChatBotButton)
- An example for `AudioButton` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/components/AudioButton.test.tsx) which may serve as a good source for reference

**Comment by tasbi03** [comment]
I’d love to contribute if no one is currently working on it.
Would it be okay for me to follow the example set by the AudioButton tests, or do you have any specific guidelines or additional functionality you’d like me to focus on? I’ll use Jest and React Testing Library for the tests unless there’s a preferred setup.
Please let me know if there’s anything else I should keep in mind or if I can go ahead with this. I’ll make sure to keep you updated on my progress.

**Comment by tjtanjin** [comment]
> I’d love to contribute if no one is currently working on it.
> 
> Would it be okay for me to follow the example set by the AudioButton tests, or do you have any specific guidelines or additional functionality you’d like me to focus on? I’ll use Jest and React Testing Library for the tests unless there’s a preferred setup.
> 
> Please let me know if there’s anything else I should keep in mind or if I can go ahead with this. I’ll make sure to keep you updated on my progress.

Hey! Yes it's a good idea to reference existing examples, partly to ensure we don't deviate too much in terms of how testing is done across different components. Feel free to clarify any time though!

**Comment by tasbi03** [comment]
hey I am not able to locate this :An example for AudioButton can be found [here](https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/components/AudioButton.test.tsx) which may serve as a good source for reference

**Comment by tjtanjin** [comment]
> hey I am not able to locate this :An example for AudioButton can be found [here](https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/components/AudioButton.test.tsx) which may serve as a good source for reference it says cannot be found. so I have one more question do you have test directory already where all the tests are located came I am not seeing or is there any other way you do this . please let me know. thank you!

Hey @tasbi03, sorry for the broken link. You can find the example [**here**](https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/components/buttons/AudioButton.test.tsx)

**Comment by tasbi03** [comment]
hey , just a question , do we have to do automated testing or manual testing ?
