### ISSUE TITLE
[Task] Add unit test cases for ChatHistoryButton component 

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#146]
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `ChatHistoryButton` component.

**Deliverable(s):**
New unit test cases that cover the testing of the `ChatHistoryButton` component.

**Additional Context:**
- The `ChatHistoryButton` components can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/src/components/ChatHistoryButton)
- An example for `AudioButton` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/components/AudioButton.test.tsx) which may serve as a good source for reference

**Comment by deeola** [comment]
Hello, can i assign this to me please also? I would love to work on it.

**Comment by tjtanjin** [comment]
> Hello, can i assign this to me please also? I would love to work on it.

Go for it!

**Comment by tjtanjin** [comment]
Completed with #170
