### ISSUE TITLE
[Task] Add unit test cases for ChatBotTooltip component 

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#147]
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `ChatBotTooltip` component.

**Deliverable(s):**
New unit test cases that cover the testing of the `ChatBotTooltip` component.

**Additional Context:**
- The `ChatBotTooltip` component can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/src/components/ChatBotTooltip)
- An example for `AudioButton` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/components/AudioButton.test.tsx) which may serve as a good source for reference

**Comment by damirgros** [comment]
Hello, can I take on this issue?
