### ISSUE TITLE
[Task] Add unit test cases for ChatMessagePrompt component

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#148]
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `ChatMessagePrompt` component which belongs within the `ChatBotBody` component.

**Deliverable(s):**
New unit test cases that cover the testing of the `ChatMessagePrompt` component.

**Additional Context:**
- The `ChatMessagePrompt` component can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/src/components/ChatBotBody/ChatMessagePrompt)
- An example for `AudioButton` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/components/AudioButton.test.tsx) which may serve as a good source for reference

**Comment by jerry-604** [comment]
Can you assign this to me?

**Comment by tjtanjin** [comment]
> Can you assign this to me?

Go for it!

**Comment by tjtanjin** [comment]
Hey @jerry-604, are you facing any problems with this issue? If so, feel free to reach out for clarifications!

**Comment by tjtanjin** [comment]
Hey @jerry-604, with hacktoberfest coming to a close very soon, I'll be leaving this issue un-assigned for any final PRs. This is to minimize leftover issues and provide an opportunity for those looking to get that last few PRs in. Feel free to continue with a PR if you're still working on this issue and I seek your kind understanding, thank you! 😊

**Comment by damirgros** [comment]
Hello, could I work on this issue?

**Comment by MadhurSaluja** [comment]
@tjtanjin can I work on this?

**Comment by tjtanjin** [comment]
> @tjtanjin can I work on this?
> 
> 

Go for it!

**Comment by MadhurSaluja** [comment]
@tjtanjin I have created a PR to close this issue, pls check it out. if there is any issue do let me know :)
