### ISSUE TITLE
[Task] Add unit test cases for MediaDisplay component

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#149]
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `MediaDisplay` component which belongs within the `ChatBotBody` component.

**Deliverable(s):**
New unit test cases that cover the testing of the `MediaDisplay` component.

**Additional Context:**
- The `MediaDisplay` component can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/src/components/ChatBotBody/MediaDisplay)
- An example for `AudioButton` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/components/AudioButton.test.tsx) which may serve as a good source for reference

**Comment by deeola** [comment]
Hello, can i assign this to me please? I would love to work on it.

**Comment by tjtanjin** [comment]
> Hello, can i assign this to me please? I would love to work on it.

Go for it!
