### ISSUE TITLE
[Task] Add unit test cases for ToastPrompt component

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#150]
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `ToastPrompt` component which belongs within the `ChatBotBody` component.

**Deliverable(s):**
New unit test cases that cover the testing of the `ToastPrompt` component.

**Additional Context:**
- The `ToastPrompt` component can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/src/components/ChatBotBody/ToastPrompt)
- An example for `AudioButton` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/components/AudioButton.test.tsx) which may serve as a good source for reference

**Comment by julianez** [comment]
Hia @tjtanjin can I take this one ?

**Comment by tjtanjin** [comment]
> Hia @tjtanjin can I take this one ?

Your PR is already ready 😂 Sure, I'll take a look when I get home!

**Comment by julianez** [comment]
I prefer to do it and then ask 😂

**Comment by tjtanjin** [comment]
> I prefer to do it and then ask 😂

Runs a minor risk of someone else coming along to indicate interest 🥹
