### ISSUE TITLE
[Task] Add unit test cases for UserCheckboxes component

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#151]
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `UserCheckboxes` component which belongs within the `ChatBotBody` component.

**Deliverable(s):**
New unit test cases that cover the testing of the `UserCheckboxes` component.

**Additional Context:**
- The `UserCheckboxes` component can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/src/components/ChatBotBody/UserCheckboxes)
- An example for `AudioButton` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/components/AudioButton.test.tsx) which may serve as a good source for reference

**Comment by corners2wall** [comment]
Assign to me please

**Comment by tjtanjin** [comment]
> Assign to me please

Go for it!

**Comment by tjtanjin** [comment]
Hey @corners2wall, are you facing problems with this issue? If so, feel free to reach out for clarifications!

**Comment by tjtanjin** [comment]
Hey @corners2wall, with hacktoberfest coming to a close very soon, I'll be leaving this issue un-assigned for any final PRs. This is to minimize leftover issues and provide an opportunity for those looking to get that last few PRs in. Feel free to continue with a PR if you're still working on this issue and I seek your kind understanding, thank you! 😊

**Comment by cleobnvntra** [comment]
Hello @tjtanjin ! I would like to work on this issue. Can you assign this to me?

**Comment by brokoli777** [comment]
Hi! I made a pull request for this issue. I tried to test some of the main functionality. Please let me know if there are any changes to be made.
