### ISSUE TITLE
[Task] Add unit test cases for UserOptions component

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#152]
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `UserOptions` component which belongs within the `ChatBotBody` component.

**Deliverable(s):**
New unit test cases that cover the testing of the `UserOptions` component.

**Additional Context:**
- The `UserOptions` component can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/src/components/ChatBotBody/UserOptions)
- An example for `AudioButton` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/components/AudioButton.test.tsx) which may serve as a good source for reference

**Comment by asmb123** [comment]
I would like to work on this.

**Comment by tjtanjin** [comment]
> I would like to work on this.

Go for it!
