### ISSUE TITLE
[Task] Add unit test cases for ChatBotFooter component

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#158]
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `ChatBotFooter` component.

**Deliverable(s):**
New unit test cases that cover the testing of the `ChatBotFooter` component.

**Additional Context:**
- The `ChatBotFooter` components can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/src/components/ChatBotFooter)
- An example for `AudioButton` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/components/AudioButton.test.tsx) which may serve as a good source for reference

**Comment by Ritesh2351235** [comment]
Hello would love to take up this issue

**Comment by tjtanjin** [comment]
> Hello would love to take up this issue 
> 
> 

Go for it!
