### ISSUE TITLE
[Task] Add unit test cases for LoadingSpinner component

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#160]
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `LoadingSpinner` component.

**Deliverable(s):**
New unit test cases that cover the testing of the `LoadingSpinner` component.

**Additional Context:**
- The `LoadingSpinner` components can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/src/components/LoadingSpinner)
- An example for `AudioButton` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/components/AudioButton.test.tsx) which may serve as a good source for reference

**Comment by Abishkardhenga** [comment]
@tjtanjin  would love to work on the issue

**Comment by tjtanjin** [comment]
> @tjtanjin  would love to work on the issue
> 
> 

Go for it!

**Comment by tjtanjin** [comment]
Hey @Abishkardhenga! Checking in to see if you're facing any problems working on the issue. Feel free to reach out!

**Comment by tjtanjin** [comment]
Hey @Abishkardhenga! With hacktoberfest drawing closer to the end, I'll be re-opening this issue for others that may be keen in this final stretch. That said, if you're still interested, feel free to open a PR soonest!

**Comment by Suvrat1629** [comment]
Hey i would like to work on this issue could you assign it to me

**Comment by tjtanjin** [comment]
> Hey i would like to work on this issue could you assign it to me

Go for it!

**Comment by cleobnvntra** [comment]
Hello @tjtanjin ! I would like to work on this issue! Could you assign this issue to me please?

**Comment by tjtanjin** [comment]
Hey @cleobnvntra, go for it! 😊
