### ISSUE TITLE
[Task] Add unit test cases for ChatHistoryLineBreak component 

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#161]
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `ChatHistoryLineBreak` component.

**Deliverable(s):**
New unit test cases that cover the testing of the `ChatHistoryLineBreak` component.

**Additional Context:**
- The `ChatHistoryLineBreak` components can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/src/components/ChatHistoryLineBreak)
- An example for `AudioButton` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/components/AudioButton.test.tsx) which may serve as a good source for reference

**Comment by yaminmomo15** [comment]
I would like to work on this.

**Comment by tjtanjin** [comment]
> I would like to work on this.

Go for it!
