### ISSUE TITLE
[Task] Add unit test cases for ChatHistoryService

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#165]
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `ChatHistoryService`.

**Deliverable(s):**
New unit test cases that cover the testing of the `VoiceService`.

**Additional Context:**
- The `ChatHistoryService` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/src/services/ChatHistoryService.tsx)
- An example for `AudioService` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/services/AudioService.test.ts) which may serve as a good source for reference

**Comment by anjumnnit** [comment]
assign this to me I will complete it. @tjtanjin

**Comment by tjtanjin** [comment]
> **Task Description:** Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__).
> 
> However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `ChatHistoryService`.
> 
> **Deliverable(s):** New unit test cases that cover the testing of the `VoiceService`.
> 
> **Additional Context:**
> 
> * The `ChatHistoryService` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/src/services/ChatHistoryService.tsx)
> * An example for `AudioService` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/services/AudioService.test.ts) which may serve as a good source for reference

Go for it!

**Comment by anjumnnit** [comment]
sorry I have unassigned this issue. U can assign it to other who can finish it early.

**Comment by Mounayer** [comment]
Hi there, I can give this a try!

**Comment by tjtanjin** [comment]
> Hi there, I can give this a try!

Go for it!
