### ISSUE TITLE
[Task] Add unit test cases for ThemeService

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#166]
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `ThemeService`.

**Deliverable(s):**
New unit test cases that cover the testing of the `ThemeService`.

**Additional Context:**
- The `ThemeService` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/src/services/ThemeService.ts)
- An example for `AudioService` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/services/AudioService.test.ts) which may serve as a good source for reference

**Comment by georgeolson92** [comment]
Hey, I'd love to contribute to this task, let me know if I can work on getting these test cases set up!

**Comment by tjtanjin** [comment]
> Hey, I'd love to contribute to this task, let me know if I can work on getting these test cases set up!

Go for it!

**Comment by georgeolson92** [comment]
Thanks for assigning! 

I've been running into this test failure when attempting to mock the Environment variables:

`    __tests__/services/ThemeService.test.ts:12:27 - error TS1343: The 'import.meta' meta-property is only allowed when the '--module' option is 'es2020', 'es2022', 'esnext', 'system', 'node16', or 'nodenext'.`

It looks like tsconfig.json already has module set to 'ESNext', so I'm wondering if you have run into this before? It seems like it should be an easy fix but I'm getting stumped.

**Comment by tjtanjin** [comment]
> Thanks for assigning! 
> 
> 
> 
> I've been running into this test failure when attempting to mock the Environment variables:
> 
> 
> 
> `    __tests__/services/ThemeService.test.ts:12:27 - error TS1343: The 'import.meta' meta-property is only allowed when the '--module' option is 'es2020', 'es2022', 'esnext', 'system', 'node16', or 'nodenext'.`
> 
> 
> 
> It looks like tsconfig.json already has module set to 'ESNext', so I'm wondering if you have run into this before? It seems like it should be an easy fix but I'm getting stumped. 

Hey, it feels like I've seen this a long time ago in another project, but I can't remember much about it 😅 I'm not on my PC to try this now, but a quick search suggests updating the jest config file with this:
```
globals: {
  'ts-jest': {
    tsconfig: 'tsconfig.json',
    useESM: true 
  },
},
```
Hopefully this is at least a step in the right direction. If you're still unable to make progress, let me know and I can try to take a look tonight 😊

**Comment by tjtanjin** [comment]
Hey @georgeolson92, trouble you to pull from master - there was an urgent bug fix for parsing css files in themes 😢

**Comment by georgeolson92** [comment]
Thanks for the feedback, I'll try that out and be sure to pull from master! :)

**Comment by georgeolson92** [comment]
Hi @tjtanjin, I think I found a workaround for the Jest issues related to Vite environment variables. The solution involves creating a separate configuration module for the Vite environment variables, allowing them to be mocked in Jest. It seems that Jest has some issues with using import.meta in Vite, so I did some research and found a solution which requires updating ThemeService.ts to utilize the new configuration.

I moved the configuration into a separate file like this:
`export const viteConfig = {
    DEFAULT_URL: import.meta.env?.VITE_THEME_BASE_CDN_URL,
    DEFAULT_EXPIRATION: import.meta.env?.VITE_THEME_DEFAULT_CACHE_EXPIRATION,
    CACHE_KEY_PREFIX: import.meta.env?.VITE_THEME_CACHE_KEY_PREFIX,
  };`

and then in the tests:
`
jest.mock("../../viteconfig", () => ({
  viteConfig: {
    DEFAULT_URL: "<_mock url here_>",
    DEFAULT_EXPIRATION: "<_number here_>",
    CACHE_KEY_PREFIX: "<_key prefix here_>",
  },
}));`

With the update, I was able to get jest to run tests and Let me know if this would be an acceptable way to move forward, or if you would prefer a different method! It looks like Vite has [their own testing framework](https://vitest.dev/) that could be useful to look into as well.

**Comment by tjtanjin** [comment]
Hey @georgeolson92, thank you for taking the time to look into this! 😊 Moving the configurations into a separate file is fine. In fact it'd be a little cleaner as well. That said, I'll have to trouble you to ensure that both `npm run unit:test` and `npm run int:test` are passing with the changes as well.

**Comment by georgeolson92** [comment]
Sounds great, thank you @tjtanjin! `npm run int:test` is passing with the changes as well, I have a pull request open if you'd like to review the code! :grin:

**Comment by tjtanjin** [comment]
Completed with #211
