### ISSUE TITLE
[Task] Add unit test cases for RcbEventService

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#167]
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `RcbEventService`.

**Deliverable(s):**
New unit test cases that cover the testing of the `RcbEventService`.

**Additional Context:**
- The `RcbEventService` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/src/services/RcbEventService.ts)
- An example for `AudioService` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/services/AudioService.test.ts) which may serve as a good source for reference

**Comment by anjumnnit** [comment]
can you please assign to me ? @tjtanjin

**Comment by tjtanjin** [comment]
> can you please assign to me ? @tjtanjin

Noted you have 2 new issues currently assigned. Let's not overwhelm you with too many issues and at the same time, keep this opportunity open for others. That said, if this issue is still unassigned when your current 2 issues are done and merged, you can pick this up.

**Comment by anjumnnit** [comment]
can you please assign this to me? As I think I am almost done with this task I will raise the PR for this just after you assign me.

**Comment by tjtanjin** [comment]
> can you please assign this to me? As I think I am almost done with this task I will raise the PR for this just after you assign me.

Noted you've released the other issues back to the public, go ahead and work on this one then!
