### ISSUE TITLE
[Task] Add unit test cases for ChatDisabledProcessor

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#169]
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `ChatDisabledProcessor`.

**Deliverable(s):**
New unit test cases that cover the testing of the `ChatDisabledProcessor`.

**Additional Context:**
- The `ChatDisabledProcessor` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/src/services/BlockService/ChatDisabledProcessor.ts)
- An example for `AudioService` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/services/AudioService.test.ts) which may serve as a good source for reference

**Comment by deeola** [comment]
can you let me handle this please?

**Comment by tjtanjin** [comment]
> can you let me handle this please?

Go for it!

**Comment by tjtanjin** [comment]
Hi @deeola! There're outstanding issues on the PR, would you be able to look at them?

**Comment by tjtanjin** [comment]
Hey @deeola, with hacktoberfest coming to a close very soon, I'll be leaving this issue un-assigned for any final PRs. This is to minimize leftover issues and provide an opportunity for those looking to get that last few PRs in. Feel free to continue with a PR if you're still working on this issue and I seek your kind understanding, thank you! 😊

**Comment by JavadAg** [comment]
hey , can you assign this to me ?

**Comment by tjtanjin** [comment]
> hey , can you assign this to me ?

Go for it!
