### ISSUE TITLE
[Bug]Text area disabled after previous chat history is loaded

### ISSUE THREAD

**Issue by yaminmomo15** [tjtanjin/react-chatbotify#172]
**Bug Description**
Text area is disabled after previous chat history is loaded.

**Steps To Reproduce**
Steps to reproduce the bug behavior:
1. Open the chat box.
2. Type {your name} in the text box and press enter to submit.
3. Reload the page.
4. Open the chat box.
5. Click "Load Chat History".
6. When previous chat history is loaded, hover the text area.
7. Text area is disabled.

**Expected behavior**
Text area is expected to be enabled after previous chat history is loaded.

**Screenshots**
<img width="389" alt="Screenshot 2024-10-08 at 4 11 58 PM" src="https://github.com/user-attachments/assets/9332def4-a8f6-42f9-a2bf-479f60f055dd">

**Desktop:**
 - macOS
 - chrome Version 129.0.6668.101

**Comment by yaminmomo15** [comment]
If this is a bug, I would like to fix this.

**Comment by tjtanjin** [comment]
Hey @yaminmomo15, thanks for flagging this out. It is indeed a bug 😢 This was likely introduced as part of the bug fix for chat history in `v2.0.0-beta.15`: https://github.com/tjtanjin/react-chatbotify/releases/tag/v2.0.0-beta.15

Go ahead and take on this task, but do help to check that previous bugs are not re-introduced. As a stretch goal, you can consider expanding on the test cases for the chat history button (feel free to create another issue if you wish). Appreciate it!

**Comment by yaminmomo15** [comment]
Sure, I will take a look.
