### ISSUE TITLE
[Task] Add unit test cases for CheckboxProcessor

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#175]
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `CheckboxProcessor`.

**Deliverable(s):**
New unit test cases that cover the testing of the `CheckboxProcessor`.

**Additional Context:**
- The `CheckboxProcessor` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/src/services/BlockService/CheckboxProcessor.ts)
- An example for `AudioService` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/services/AudioService.test.ts) which may serve as a good source for reference

**Comment by tjtanjin** [comment]
> Hi @tjtanjin , please assign me to this issue

Go for it!

**Comment by andreykishtov** [comment]
Hi @tjtanjin, i created pull request with requested tested

**Comment by tjtanjin** [comment]
Completed with #200
