### ISSUE TITLE
[Task] Add unit test cases for ComponentProcessor

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#176]
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `ComponentProcessor`.

**Deliverable(s):**
New unit test cases that cover the testing of the `ComponentProcessor`.

**Additional Context:**
- The `ComponentProcessor` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/src/services/BlockService/ComponentProcessor.ts)
- An example for `AudioService` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/services/AudioService.test.ts) which may serve as a good source for reference

**Comment by yaminmomo15** [comment]
I would like to work on this.

**Comment by tjtanjin** [comment]
> I would like to work on this.

Go for it!
