### ISSUE TITLE
[Task] Add unit test cases for FunctionProcessor

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#177]
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `FunctionProcessor`.

**Deliverable(s):**
New unit test cases that cover the testing of the `FunctionProcessor`.

**Additional Context:**
- The `FunctionProcessor` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/src/services/BlockService/FunctionProcessor.ts)
- An example for `AudioService` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/services/AudioService.test.ts) which may serve as a good source for reference

**Comment by Pratik00019** [comment]
Hi @tjtanjin,

Could you please assign this issue to me? I have experience working with Jest and would love to contribute.

Thank you!

**Comment by tjtanjin** [comment]
> Hi @tjtanjin,
> 
> 
> 
> Could you please assign this issue to me? I have experience working with Jest and would love to contribute.
> 
> 
> 
> Thank you!

Go for it!

**Comment by Pratik00019** [comment]
@tjtanjin I have raised a PR. Can you please review and accept it, and apply the `hacktoberfest-accepted` label? Thank you.

**Comment by tjtanjin** [comment]
Completed with #181
