### ISSUE TITLE
[Task] Add unit test cases for IsSensitiveProcessor

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#183]
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `IsSensitiveProcessor`.

**Deliverable(s):**
New unit test cases that cover the testing of the `IsSensitiveProcessor`.

**Additional Context:**
- The `IsSensitiveProcessor` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/src/services/BlockService/IsSensitiveProcessor.ts)
- An example for `AudioService` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/services/AudioService.test.ts) which may serve as a good source for reference

**Comment by anjumnnit** [comment]
please assign this to me. @tjtanjin

**Comment by tjtanjin** [comment]
> please assign this to me. @tjtanjin

Noted you have 2 new issues currently assigned. Let's not overwhelm you with too many issues and at the same time, keep this opportunity open for others. That said, if this issue is still unassigned when your current 2 issues are done and merged, you can pick this up.

**Comment by anjumnnit** [comment]
> > please assign this to me. @tjtanjin
> 
> Noted you have 2 new issues currently assigned. Let's not overwhelm you with too many issues and at the same time, keep this opportunity open for others. That said, if this issue is still unassigned when your current 2 issues are done and merged, you can pick this up.

np thx :)

**Comment by anandxs** [comment]
Hi. I would like this assigned to me.

**Comment by tjtanjin** [comment]
> Hi. I would like this assigned to me. @tjtanjin

Go for it!
