### ISSUE TITLE
[Task] Add unit test cases for OptionProcessor

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#185]
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `OptionProcessor`.

**Deliverable(s):**
New unit test cases that cover the testing of the `OptionProcessor`.

**Additional Context:**
- The `OptionProcessor` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/src/services/BlockService/OptionProcessor.ts)
- An example for `AudioService` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/services/AudioService.test.ts) which may serve as a good source for reference

**Comment by Mila2999** [comment]
please assign me this issue

**Comment by tjtanjin** [comment]
> please assign me this issue

Go for it!

**Comment by Mila2999** [comment]
Hi @tjtanjin , i created pull request[PR](https://github.com/tjtanjin/react-chatbotify/pull/201)

**Comment by tjtanjin** [comment]
Completed with #201
