### ISSUE TITLE
[Task] Add unit test cases for PathProcessor

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#186]
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `PathProcessor`.

**Deliverable(s):**
New unit test cases that cover the testing of the `PathProcessor`.

**Additional Context:**
- The `PathProcessor` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/src/services/BlockService/PathProcessor.ts)
- An example for `AudioService` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/services/AudioService.test.ts) which may serve as a good source for reference

**Comment by Pratik00019** [comment]
Hello @tjtanjin , Can you also pls assign this issue to me ?

**Comment by tjtanjin** [comment]
> Hello @tjtanjin , Can you also pls assign this issue to me ?

Go for it!

**Comment by tjtanjin** [comment]
Hey @Pratik00019, with hacktoberfest coming to a close very soon, I'll be leaving this issue un-assigned for any final PRs. This is to minimize leftover issues and provide an opportunity for those looking to get that last few PRs in. Feel free to continue with a PR if you're still working on this issue and I seek your kind understanding, thank you! 😊

**Comment by aamfahim** [comment]
Hello @tjtanjin! I was able to write unit tests for this service. I will be making an PR soon.
