### ISSUE TITLE
[Task] Add unit test cases for buttonBuilder utils

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#194]
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `buttonBuilder` utils.

**Deliverable(s):**
New unit test cases that cover the testing of the `buttonBuilder`.

**Additional Context:**
- The `buttonBuilder` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/src/utils/buttonBuilder.tsx)
- An example for `messageBuilder` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/utils/messageBuilder.test.ts) which may serve as a good source for reference

**Comment by Sachita007** [comment]
Could you assign this to me? I would like to work on it.

**Comment by tjtanjin** [comment]
> Could you assign this to me? I would like to work on it.

Go for it!

**Comment by tjtanjin** [comment]
Hey @Sachita007, with hacktoberfest coming to a close very soon, I'll be leaving this issue un-assigned for any final PRs. This is to minimize leftover issues and provide an opportunity for those looking to get that last few PRs in. Feel free to continue with a PR if you're still working on this issue and I seek your kind understanding, thank you! 😊

**Comment by Nandinibajaj16** [comment]
@tjtanjin can you please assign this to me?

**Comment by Nandinibajaj16** [comment]
@tjtanjin I want to take this up, can you assign to me?

**Comment by tjtanjin** [comment]
> @tjtanjin I want to take this up, can you assign to me?

Go for it!
