### ISSUE TITLE
[Task] Add unit test cases for configParser utils

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#195]
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `configParser` utils.

**Deliverable(s):**
New unit test cases that cover the testing of the `configParser`.

**Additional Context:**
- The `configParser` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/src/utils/configParser.ts)
- An example for `messageBuilder` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/utils/messageBuilder.test.ts) which may serve as a good source for reference

**Comment by andreykishtov** [comment]
would love to add take this issue

**Comment by tjtanjin** [comment]
> @tjtanjin would love to add take this issue

Go for it!

**Comment by andreykishtov** [comment]
Hi @tjtanjin , added tests in this [PR](https://github.com/tjtanjin/react-chatbotify/pull/208)

**Comment by tjtanjin** [comment]
Completed with #208
