### ISSUE TITLE
[Task] Add unit test cases for displayChecker utils

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#196]
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `displayChecker` utils.

**Deliverable(s):**
New unit test cases that cover the testing of the `displayChecker`.

**Additional Context:**
- The `displayChecker` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/src/utils/displayChecker.ts)
- An example for `messageBuilder` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/utils/messageBuilder.test.ts) which may serve as a good source for reference

**Comment by damirgros** [comment]
Hello, can I work on this issue?

**Comment by tjtanjin** [comment]
> Hello, can I work on this issue?

Go for it!
