### ISSUE TITLE
[Task] Add unit test cases for idGenerator utils

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#197]
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `idGenerator` utils.

**Deliverable(s):**
New unit test cases that cover the testing of the `idGenerator`.

**Additional Context:**
- The `idGenerator` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/src/utils/idGenerator.ts)
- An example for `messageBuilder` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/utils/messageBuilder.test.ts) which may serve as a good source for reference

**Comment by rahulrk-dev** [comment]
Hey @tjtanjin, I would like to work on this

**Comment by tjtanjin** [comment]
> Hey @tjtanjin, I would like to work on this

Go for it!
