### ISSUE TITLE
[Task] Add unit test cases for markupParser utils

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#198]
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `markupParser` utils.

**Deliverable(s):**
New unit test cases that cover the testing of the `markupParser`.

**Additional Context:**
- The `markupParser` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/src/utils/markupParser.ts)
- An example for `messageBuilder` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/utils/messageBuilder.test.ts) which may serve as a good source for reference

**Comment by vaibhavj2111** [comment]
I would like to contribute to this issue. Please assign this to me.

**Comment by tjtanjin** [comment]
> I would like to contribute to this issue. Please assign this to me.

Go for it!
