### ISSUE TITLE
[Task] Add unit test cases for mediaFileParser utils

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#199]
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `mediaFileParser` utils.

**Deliverable(s):**
New unit test cases that cover the testing of the `mediaFileParser`.

**Additional Context:**
- The `mediaFileParser` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/src/utils/mediaFileParser.ts)
- An example for `messageBuilder` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/utils/messageBuilder.test.ts) which may serve as a good source for reference

**Comment by rahulrk-dev** [comment]
Hey @tjtanjin, I would like to work on this one

**Comment by tjtanjin** [comment]
> Hey @tjtanjin, I would like to work on this one

Go for it!

**Comment by Pratik00019** [comment]
Hey @tjtanjin  Can you assign this issue to me? I will complete it asap

**Comment by tjtanjin** [comment]
> Hey @tjtanjin  Can you assign this issue to me? I will complete it asap

Hey @Pratik00019! This issue is taken and a PR has already been opened. If you're keen there are still a few unassigned issues lying around!
