### ISSUE TITLE
[Bug] TTS reads out markup tags

### ISSUE THREAD

**Issue by nahu02** [tjtanjin/react-chatbotify#210]
**Bug Description**
When using the react-chatbotify library with Audio (text-to-speech) enabled, the TTS engine incorrectly reads out HTML tags and markup present in the bot's messages. This results in a poor user experience as HTML tags are not meant to be read aloud.

**Steps To Reproduce**
Steps to reproduce the bug behavior:
1. Create a new React project
2. Install react-chatbotify
3. Copy this component into your project
4. Render the `MinimalReproduction` component
5. Open the chatbot and listen to the TTS output for the first message. Depending on your browser you may have to disable and enable it again if autoplaying audio is prevented.

```typescript
const MinimalReproduction = () => {
  const flow = {
    start: {
      message: "This is <b>bold</b> and <i>italic</i>. <a href='https://example.com'>This is a link</a>.",
      path: "start"
    },
  };

  return (
    <ChatBot
      flow={flow}
      settings={{
        audio: { disabled: false, defaultToggledOn: true },
        botBubble: { dangerouslySetInnerHtml: true }
      }}
    />
  );
};
```

**Expected behavior**
The TTS should ignore HTML tags and only read the actual content. For images, it should read the alt text. In most other cases, it should read the content without the tags.

**Actual behavior**
The TTS reads out the HTML tags along with the content, for example, saying "less than b greater than bold text less than slash b greater than" instead of just "bold text".

**Desktop (please complete the following information):**
- OS: Linux, Windows
- Browser: Firefox (Linux), Chrome (Windows)

**Comment by tjtanjin** [comment]
Hey @nahu02, thank you for the bug report. I'll try to take a look at this within the next couple of days, hopefully an easy fix.

**Comment by tjtanjin** [comment]
Hey @nahu02, this is now fixed. Closing this issue - it will be included in the next release 😊
