### ISSUE TITLE
[Task] Expand unit test for markupParser

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#213]
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to expand the test cases for the `markupParser`.

**Deliverable(s):**
Extend current unit test cases to cover the new `stripHtml` function within `markupParser`.

**Additional Context:**
- The `markupParser` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/src/utils/markupParser.ts)
- The previous PR for adding unit test to `markupParser` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/issues/198)

**Comment by georgeolson92** [comment]
Hey, now that the ThemeService tests have been merged I'd love to help with this one if nobody's started working on it yet!

**Comment by tjtanjin** [comment]
> Hey, now that the ThemeService tests have been merged I'd love to help with this one if nobody's started working on it yet!

Go for it!

**Comment by tjtanjin** [comment]
Completed with #217

**Comment by tjtanjin** [comment]
Completed with #220
