### ISSUE TITLE
[Task] Add unit test cases for ChatBotContainer component

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#222]
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `ChatBotContainer` component.

**Deliverable(s):**
New unit test cases that cover the testing of the `ChatBotContainer` component.

**Additional Context:**
- The `ChatBotContainer` component can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/src/components/ChatBotContainer.tsx)
- An example for `AudioButton` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/components/buttons/AudioButton.test.tsx) which may serve as a good source for reference

**Comment by tjtanjin** [comment]
> Hey, I'm down to work on this one next if you need someone to help with getting these test cases added!

That'll be great!

**Comment by georgeolson92** [comment]
Hi @tjtanjin, thanks for assigning me! Been working on getting some tests set up but keep running into this error when I seem to have a test that should be able to run: 

"Jest worker encountered 4 child process exceptions, exceeding retry limit"

Let me know if you have any insight into what might cause this!

**Comment by tjtanjin** [comment]
> Hi @tjtanjin, thanks for assigning me! Been working on getting some tests set up but keep running into this error when I seem to have a test that should be able to run:
> 
> "Jest worker encountered 4 child process exceptions, exceeding retry limit"
> 
> Let me know if you have any insight into what might cause this!

Hey @georgeolson92, I've not countered this issue before but looking around it seems to imply resource issues. Have you tried setting jest `maxWorkers` to something like `25%`?

**Comment by georgeolson92** [comment]
Hi @tjtanjin thank you for the response! It was due to an issue with the AudioContext(), I've addressed that and have been able to get all the tests running as intended and opened a pull request!
