### ISSUE TITLE
[Task] Add unit test cases for ChatBotLoader component

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#223]
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `ChatBotLoader` component.

**Deliverable(s):**
New unit test cases that cover the testing of the `ChatBotLoader` component.

**Additional Context:**
- The `ChatBotLoader` component can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/src/components/ChatBotLoader.tsx)
- An example for `AudioButton` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/components/buttons/AudioButton.test.tsx) which may serve as a good source for reference

**Comment by Suvrat1629** [comment]
Hey could you assign this issue to me i would like to work on it

**Comment by tjtanjin** [comment]
> Hey could you assign this issue to me i would like to work on it
> 
> 
> 
> 

Go for it!

**Comment by Suvrat1629** [comment]
@tjtanjin Hey I needed some help, I have made the ChatBotLoader.test.tsx file and written the testcases for it. But when i try to run the testcases I am getting an error
![Screenshot 2024-10-20 105941](https://github.com/user-attachments/assets/eb41391e-0975-4483-9557-1b69bd493ead)
This is the error I am getting. How do i go about this because I have already tried changing the "target": "es2015"  to "target": "esnext" also (i changed it back to default) but it still doesn't seem to work

**Comment by Suvrat1629** [comment]
Hey I needed some help. I have written code for ChatBotLoader.test.tsx but I am getting a weird error for which i am not finding a way to solve it,
![Screenshot 2024-10-20 105941](https://github.com/user-attachments/assets/1945e1a4-1850-485f-a12f-1cfddd2ffbd3)
this is the error could you help me with this

**Comment by tjtanjin** [comment]
> Hey I needed some help. I have written code for ChatBotLoader.test.tsx but I am getting a weird error for which i am not finding a way to solve it, ![Screenshot 2024-10-20 105941](https://private-user-images.githubusercontent.com/140749446/378163368-1945e1a4-1850-485f-a12f-1cfddd2ffbd3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MjA5MzIsIm5iZiI6MTcyOTQyMDYzMiwicGF0aCI6Ii8xNDA3NDk0NDYvMzc4MTYzMzY4LTE5NDVlMWE0LTE4NTAtNDg1Zi1hMTJmLTFjZmRkZDJmZmJkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMFQxMDM3MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NjFjNDk5NzBkY2Q3MmIyYjYyZGNjNTVkODk4ZWZjNDQ1MTNiYmQwZWQyNjJkMGIzZDhiYmM5ZTQ2ODY3OTQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lvvMteI3M28O9h0SNAcndnCAPGkJxHLpFEppJNlCZC8) this is the error could you help me with this

Hey! It's a bit hard to tell without seeing what you currently have written for your test cases. Though specifically for vite config, you may find this a good reference: https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/services/ThemeService.test.ts

**Comment by tjtanjin** [comment]
Hey @Suvrat1629, with hacktoberfest coming to a close very soon, I'll be leaving this issue un-assigned for any final PRs. This is to minimize leftover issues and provide an opportunity for those looking to get that last few PRs in. Feel free to continue with a PR if you're still working on this issue and I seek your kind understanding, thank you! 😊

**Comment by MadhurSaluja** [comment]
@tjtanjin Hey can I work on this?

**Comment by tjtanjin** [comment]
> @tjtanjin Hey can I work on this?
> 
> 

Go for it!
