### ISSUE TITLE
[Task] Add unit test cases for useStylesInternal hook

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#225]
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `useStylesInternal` hook.

**Deliverable(s):**
New unit test cases that cover the testing of the `useStylesInternal` hook.

**Additional Context:**
- Hooks API can be found [**here**](https://react-chatbotify.com/docs/api/hooks)
- Existing unit test for hooks can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__/hooks) which may serve as a good source for reference.

**Comment by mashazyu** [comment]
Hello @tjtanjin ,

If the issues still available, I'd like to work on it.

**Comment by tjtanjin** [comment]
> Hello @tjtanjin ,
> 
> 
> 
> If the issues still available, I'd like to work on it.

Go for it!

**Comment by tjtanjin** [comment]
Hey @mashazyu, with hacktoberfest coming to a close very soon, I'll be leaving this issue un-assigned for any final PRs. This is to minimize leftover issues and provide an opportunity for those looking to get that last few PRs in. Feel free to continue with a PR if you're still working on this issue and I seek your kind understanding, thank you! 😊

**Comment by mashazyu** [comment]
@tjtanjin 

Thank you very much for pinging me! And I apologize, something came up and I didn't communicate it.

I opened a PR with test. What do you think?
