### ISSUE TITLE
[Task] Add unit test cases for BotStatesContext 

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#227]
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `BotStatesContext`.

**Deliverable(s):**
New unit test cases that cover the testing of the `BotStatesContext`.

**Additional Context:**
- The `BotStatesContext` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/src/context/BotStatesContext.tsx)
- An example for `BotRefsContext` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/context/BotRefsContext.test.tsx) which may serve as a good source for reference

**Comment by Suvrat1629** [comment]
Hey i would like to work on this issue

**Comment by tjtanjin** [comment]
> Hey i would like to work on this issue could you assign this to me

Go for it!

**Comment by tjtanjin** [comment]
Completed with #249
