### ISSUE TITLE
[Task] Add unit test cases for PathsContext

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#230]
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `PathsContext`.

**Deliverable(s):**
New unit test cases that cover the testing of the `PathsContext`.

**Additional Context:**
- The `PathsContext` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/src/context/PathsContext.tsx)
- An example for `BotRefsContext` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/context/BotRefsContext.test.tsx) which may serve as a good source for reference

**Comment by rahulrk-dev** [comment]
Hey @tjtanjin, I would like to work on this one

**Comment by tjtanjin** [comment]
> Hey @tjtanjin, I would like to work on this one

Go for it!
