### ISSUE TITLE
[Task] Add unit test cases for SettingsContext 

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#231]
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `SettingsContext`.

**Deliverable(s):**
New unit test cases that cover the testing of the `SettingsContext`.

**Additional Context:**
- The `SettingsContext` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/src/context/SettingsContext.tsx)
- An example for `BotRefsContext` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/context/BotRefsContext.test.tsx) which may serve as a good source for reference

**Comment by sivasuriyankumarasamy** [comment]
Hi @tjtanjin 

I would like to work on this. Can you assign this issue to me.

**Comment by Goketech** [comment]
@sivasuriyankumarasamy I just made a pr for this issue

**Comment by tjtanjin** [comment]
> Hi @tjtanjin 
> 
> 
> 
> I would like to work on this. Can you assign this issue to me.

Go for it!

**Comment by tjtanjin** [comment]
> @sivasuriyankumarasamy I just made a pr for this issue
> 
> 

Hey @Goketech, understand you opened a PR but @sivasuriyankumarasamy expressed interest first and the issue was not assigned. Given that you are next in line, you can keep your PR open, which will still be accepted in the event that the issue is unassigned. Seek your understanding!
