### ISSUE TITLE
[Task] Add unit test cases for StylesContext

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#232]
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `StylesContext`.

**Deliverable(s):**
New unit test cases that cover the testing of the `StylesContext`.

**Additional Context:**
- The `StylesContext` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/src/context/StylesContext.tsx)
- An example for `BotRefsContext` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/context/BotRefsContext.test.tsx) which may serve as a good source for reference

**Comment by Suvrat1629** [comment]
I have created a PR for this issue please review it.
