### ISSUE TITLE
[Task] Add unit test cases for ToastsContext 

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#233]
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `ToastsContext`.

**Deliverable(s):**
New unit test cases that cover the testing of the `ToastsContext`.

**Additional Context:**
- The `ToastsContext` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/src/context/ToastsContext.tsx)
- An example for `BotRefsContext` can be found [**here**](https://github.com/tjtanjin/react-chatbotify/blob/main/__tests__/context/BotRefsContext.test.tsx) which may serve as a good source for reference

**Comment by Goketech** [comment]
I created a pull request for this issue [pr 235](https://github.com/tjtanjin/react-chatbotify/pull/235)
