### ISSUE TITLE
[Task] Add unit test cases for useIsDesktopInternal hook 

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#239]
**Task Description:**
Currently, we run unit tests using jest which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__). 

However, the test cases are not yet comprehensive enough and work can be done to cover more grounds. Specifically for this issue, we hope to add test cases for the `useIsDesktopInternal` hook.

**Deliverable(s):**
New unit test cases that cover the testing of the `useIsDesktopInternal` hook.

**Additional Context:**
- Hooks API can be found [**here**](https://react-chatbotify.com/docs/api/hooks)
- Existing unit test for hooks can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__/hooks) which may serve as a good source for reference.

**Comment by Nandinibajaj16** [comment]
@tjtanjin I'd like to take this up

**Comment by Nandinibajaj16** [comment]
Hey @tjtanjin I'd like to take this up
