### ISSUE TITLE
I couldnt able to get data in object format 

### ISSUE THREAD

**Issue by habibunnish** [tjtanjin/react-chatbotify#241]
**Bug Description**
Provide a clear and concise description of the bug.

**Steps To Reproduce**
Steps to reproduce the bug behavior:
"use client";
import { lazy, Suspense, useEffect, useState } from "react";
const ChatBot = lazy(() => import("react-chatbotify"));

const ChatBot = () => {
  const [isLoaded, setIsLoaded] = useState(false);

  useEffect(() => {
    setIsLoaded(true);
  }, []);

  const flow = {
    start: {
      message: "Hey! Welcome to shopping Assistant!",
      path: "loop",
    },
    loop: {
      message: async () => {
          return <div><p>hello world</p></div>
      },
      path: "loop", // Continue the loop after response
    },
  };

  return (
    <>
      {isLoaded && (
        <Suspense fallback={<div>Loading...</div>}>
          <ChatBot
            styles={{
              chatIconStyle: {
                width: "50px",
                height: "50px",
                backgroundColor: "#BF40BF",
                marginBottom: "50px",
              },
              chatMessagePromptStyle: { backgroundColor: "red" },
              tooltipStyle: {
                backgroundColor: "#BF40BF",
                fontSize: "16px",
                padding: "10px 20px 10px 20px",
                right: "90px",
                bottom: "20px",
                marginBottom: "53px",
              },
              chatButtonStyle: {
                marginBottom: "55px",
              },
            }}
            settings={{
              header: {
                title: (
                  <div
                    style={{
                      cursor: "pointer",
                      margin: 0,
                      fontSize: 20,
                      fontWeight: "bold",
                    }}
                  >
                   shopping site
                  </div>
                )
              },
              tooltip: {
                mode: "CLOSE",
                text: "Your Shopping Assistant.",
              },
              general: {
                embedded: false,
                showFooter: false,
                primaryColor: "#636466",
                secondaryColor: "#855AA6",
              },
              },
              notification: {
                disabled: true,
              },
              chatHistory: { storageKey: "example_smart_conversation" },
            }}
            flow={flow}
          />
        </Suspense>
      )}
    </>
  );
};

export default ChatBot;

**Expected behavior**
I need data in object manner but its only supporting in string 

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]

**Mobile (please complete the following information):**
 - Device: [e.g. iPhone12]
 - Browser: [e.g. edge, firefox]

**Comment by habibunnish** [comment]
on here its only accepting string messages

const flow = {
start: {
message: "Hey! Welcome to shopping Assistant!",
path: "loop",
},
loop: {
message: async () => {
return "hello world"
},
path: "loop", // Continue the loop after response
},
};

but if i try to pass object like this as div element its not showing in ui 

const flow = {
start: {
message: "Hey! Welcome to shopping Assistant!",
path: "loop",
},
loop: {
message: async () => {
return <div><p>hello world</p></div>
},
path: "loop", // Continue the loop after response
},
};

**Comment by habibunnish** [comment]
can u show me with an example how to do it

**Comment by tjtanjin** [comment]
> can u show me with an example how to do it
> 
> 

You can take a look at this example: https://react-chatbotify.com/docs/examples/custom_component

**Comment by habibunnish** [comment]
yeah ok thanks alot @tjtanjin

**Comment by tjtanjin** [comment]
Feel free to reach out again if you need more clarifications!

**Comment by habibunnish** [comment]
yeah sure.

**Comment by habibunnish** [comment]
const flow = {
    start: {
      message: "Hey! Welcome to Rufus-Gpt!",
      path: "loop",
    },
    loop: {
      component: () => (
        <div>
          <p>Hello world</p>
        </div>
      ),
      path: "loop",
    },
  };

  return (
    <>
      {isLoaded && (
        <Suspense fallback={<div>Loading...</div>}>
          <ChatBot
            styles={{
              chatIconStyle: {
                width: "50px",
                height: "50px",
                backgroundColor: "#BF40BF",
                marginBottom: "50px",
              },
              chatMessagePromptStyle: { backgroundColor: "red" },
              tooltipStyle: {
                backgroundColor: "#BF40BF",
                fontSize: "16px",
                padding: "10px 20px 10px 20px",
                right: "90px",
                bottom: "20px",
                marginBottom: "53px",
              },
              chatButtonStyle: {
                marginBottom: "55px",
              },
            }}
            settings={{
              header: {
                title: (
                  <div
                    style={{
                      cursor: "pointer",
                      margin: 0,
                      fontSize: 20,
                      fontWeight: "bold",
                    }}
                  >
                    shop new
                  </div>
                )

              },
              tooltip: {
                mode: "CLOSE",
                text: "Your Shopping Assistant .",
              },
              general: {
                embedded: false,
                showFooter: false,
                primaryColor: "#636466",
                secondaryColor: "#855AA6",
              }              notification: {
                disabled: true,
              },
              chatHistory: { storageKey: "example_smart_conversation" },
            }}
            flow={flow}
          />
        </Suspense>
      )}
    </>
  );
  
  I have written my code like this but still its not showing in ui where am i going wrong can you plz telll me

**Comment by habibunnish** [comment]
const flow = {
    start: {
      message: "Hey! Welcome to Gpt!",
      path: "loop",
    },
    loop: {
      component: () => (
        <div> <p>Hello world</p></div>
      ),
      path: "loop", // Keep the flow looping
    },
  };

  return (
    <>
      {isLoaded && (
        <Suspense fallback={<div>Loading...</div>}>
          <ChatBot
            styles={{
              chatIconStyle: {
                width: "50px",
                height: "50px",
                backgroundColor: "#BF40BF",
                marginBottom: "50px",
              },
              chatMessagePromptStyle: { backgroundColor: "red" },
              tooltipStyle: {
                backgroundColor: "#BF40BF",
                fontSize: "16px",
                padding: "10px 20px 10px 20px",
                right: "90px",
                bottom: "20px",
                marginBottom: "53px",
              },
              chatButtonStyle: {
                marginBottom: "55px",
              },
            }}
            settings={{
              header: {
                title: (
                  <div
                    style={{
                      cursor: "pointer",
                      margin: 0,
                      fontSize: 20,
                      fontWeight: "bold",
                    }}
                  >
                    Aspire Auras
                  </div>
                ),
   
              },
              tooltip: {
                mode: "CLOSE",
                text: "Your Shopping Assistant ",
              },
              general: {
                embedded: false,
                showFooter: false,
                primaryColor: "#636466",
                secondaryColor: "#855AA6",
              },
              chatButton: {
                icon: "/auras-white.png",
              },
              notification: {
                disabled: true,
              },
              chatHistory: { storageKey: "example_smart_conversation" },
            }}
            flow={flow}
          />
        </Suspense>
      )}
    </>
  );
  
  this is the complete code

**Comment by tjtanjin** [comment]
You're not passing in an element into `component`, check the syntax and reference the example 🥹

**Comment by habibunnish** [comment]
component: () => (
        <div>
          <p>Hello world</p>
        </div>
      ),
      
      inside <div/>  element and <p/> element iam passing  hello world

**Comment by tjtanjin** [comment]
> component: () => (
> 
> 
> Hello world
> 
> 
> 
> ),
> ```
>   inside <div/>  element and <p/> element iam passing  hello world 
> ```

There's no `<div>` or `<p>` seen here :3

**Comment by habibunnish** [comment]
i dont know why its not showing to you when iam sending comment it erasing the div element from component and going

**Comment by tjtanjin** [comment]
> i dont know why its not showing to you when iam sending comment it erasing the div element from component and going

Wrap your entire code with a codeblock, or perhaps take a screenshot

**Comment by tjtanjin** [comment]
> <img alt="sceenshot1" width="300" src="https://private-user-images.githubusercontent.com/121093383/378699916-90383771-0759-4951-9357-b01a31d10090.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1NzczOTksIm5iZiI6MTcyOTU3NzA5OSwicGF0aCI6Ii8xMjEwOTMzODMvMzc4Njk5OTE2LTkwMzgzNzcxLTA3NTktNDk1MS05MzU3LWIwMWEzMWQxMDA5MC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMlQwNjA0NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYTcwYTc0MjQ1NWVhMmFjN2ZiZGUxZmM5YTI3OGZiZDMxMmI2YmRhNDVhMTZlMzM4ZjQ1ZGZmYWJkYjQ5NzA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Uig1BdlT7qEoPTYu8YXx3B7OknDLDCKfKJV2b1iYV5A">

What version of the library are you on?

**Comment by habibunnish** [comment]
"react-chatbotify": "^2.0.0-beta.7"

**Comment by tjtanjin** [comment]
> "react-chatbotify": "^2.0.0-beta.7"

Try moving to beta.20. If that still doesn't work, is the component not appearing for you completely or is there some error or anything else happening?

**Comment by habibunnish** [comment]
I got the soln now its working as i expected i created separate customMessageComponent and called that component
