### ISSUE TITLE
[Feat]: add a script that allows testing a single unit test

### ISSUE THREAD

**Issue by Mounayer** [tjtanjin/react-chatbotify#259]
**Is your feature request related to a problem? Please describe.**
There are many unit tests, whenever one would want to add more tests to a certain file, or more test files, it takes quite a long time to run all of the tests just to see the result of the newly added one.

**Describe the solution you'd like**
Adding a new script `"unit:test:single": "jest --findRelatedTests"`

This script allows running a single test file that the user provides, example usage would be:

```bash
npm run unit:test:single ChatHistoryService.test.ts
```

This would simply only run the test file provided!

**Describe alternatives you've considered**
The only alternative is to run all of the tests, which takes quite a bit of time, and can be a little frustrating when writing new tests!

**Additional context**
The idea is to simply offer a more friendly development experience for the developer!

**Comment by tjtanjin** [comment]
Hey @Mounayer! If you'd like to, you can include this in what I suppose is the [issue](https://github.com/tjtanjin/react-chatbotify/issues/165) you're working on 😝

**Comment by Mounayer** [comment]
> Hey @Mounayer! If you'd like to, you can include this in what I suppose is the [issue](https://github.com/tjtanjin/react-chatbotify/issues/165) you're working on 😝

I gotchu! 👍
