### ISSUE TITLE
facing issues with the flow operation 

### ISSUE THREAD

**Issue by habibunnish** [tjtanjin/react-chatbotify#262]
**Bug Description**
I am not getting response in sequence way, when iam trying to search 2nd time anything thn its not hitting my endpoint.

**Expected behavior**
I want my flow to be in sequence way properly whenever user comes and search anything .

**Screenshots**
<img width="608" alt="1" src="https://github.com/user-attachments/assets/2fa97720-0b28-4447-8a5b-82489807ebab">
<img width="572" alt="2 1" src="https://github.com/user-attachments/assets/15fd4a24-91e6-468c-9ea5-71f8452ebcf9">
<img width="591" alt="2" src="https://github.com/user-attachments/assets/1c907c1e-591c-45a8-8649-7772ce45d08c">
<img width="535" alt="3" src="https://github.com/user-attachments/assets/02beb240-2187-41aa-9352-b610e31cba76">
<img width="496" alt="4" src="https://github.com/user-attachments/assets/0f1b5fda-6ee2-4ce0-bbd3-0f3c3bd58eb5">
<img width="447" alt="5" src="https://github.com/user-attachments/assets/e11800f2-edaa-494e-88e3-48a6efb10c3c">

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]

**Mobile (please complete the following information):**
 - Device: [e.g. iPhone12]
 - Browser: [e.g. edge, firefox]

**Additional context**

**Comment by tjtanjin** [comment]
Hey @habibunnish, are you able to provide more context e.g. with gifs and screenshots of the bot itself? The code is very long and doesn't really shed much light on the issue. Thanks!

**Comment by habibunnish** [comment]
yeah sure here is screenshot of my bot application
<img width="278" alt="6" src="https://github.com/user-attachments/assets/19426a22-a6ab-4f5f-ae65-c2f6accfb3fc">
<img width="269" alt="7" src="https://github.com/user-attachments/assets/7c7121b4-556e-4a61-ac31-8b669f08e45b">
<img width="275" alt="8" src="https://github.com/user-attachments/assets/9b81009c-f722-452a-8c53-8d4af685cfb9">
<img width="277" alt="9" src="https://github.com/user-attachments/assets/bc450042-d55f-4af5-aebe-775a6317cf38">

**Comment by tjtanjin** [comment]
@habibunnish Hmm from your application screenshots, it seems like you're getting the responses intended. When you ask for boots/laptops they actually give the corresponding replies. Perhaps you can provide more details/clarifications on what the issue is? It would be helpful to if you could also **describe the intended behavior**, then **describe the observed behavior**. That way we'd have a clearer idea as well. Thanks!

**Comment by habibunnish** [comment]
Intended behavior:-   user should be able to interact with chat bot seemlessly everytime  and its should fetch data always instead of generating  response odd time only 
observed behavior:-  shown here is like when i try to interact with chatbot second time then  its not fetching data  properly ,

**Comment by tjtanjin** [comment]
> Intended behavior:- user should be able to interact with chat bot seemlessly everytime and its should fetch data always instead of generating response odd time only observed behavior:- shown here is like when i try to interact with chatbot second time then its not fetching data properly ,

Hmm have you tried the `transition: 0` mentioned above? The reason you are having to type twice before getting responses is because the `showResponses` block does not automatically path to the `start` block again until it gets a user input. If you want it to automatically return to start, you need the `transition` attribute. Otherwise, the first input brings you back to the `start` block, and the second input then processes the logic inside `start` block which explains what you're currently observing.

**Comment by habibunnish** [comment]
yeah i added but its didnt worked
<img width="436" alt="1 1" src="https://github.com/user-attachments/assets/20756283-1727-4239-9ef1-b1fa59688427">

**Comment by tjtanjin** [comment]
> yeah i added but its didnt worked <img alt="1 1" width="436" src="https://private-user-images.githubusercontent.com/121093383/384688519-20756283-1727-4239-9ef1-b1fa59688427.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNDIzNzIsIm5iZiI6MTczMTI0MjA3MiwicGF0aCI6Ii8xMjEwOTMzODMvMzg0Njg4NTE5LTIwNzU2MjgzLTE3MjctNDIzOS05ZWYxLWIxZmE1OTY4ODQyNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQxMjM0MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYjVkZDNlZTU0YzU3MmY1N2NmN2NhMGZhZDg1MjJjNmVhMzY2MTRhNzgzNmI2MThmN2Q1MTY2YTI3NWZmMjUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.g548y28ZkHGuPbNiWIx9UvH2o058n30jolLq0qZC_Uw">

The `transition` attribute isn't added based on your screenshot, there's only `component` and `path` attributes. Usage for `transition` can be found here: https://react-chatbotify.com/docs/api/attributes#transition

**Comment by habibunnish** [comment]
ok let me check it

**Comment by habibunnish** [comment]
still not working
<img width="419" alt="1 3" src="https://github.com/user-attachments/assets/5c042fa2-1edc-461e-9f3a-cdaae070f598">

**Comment by tjtanjin** [comment]
> still not working <img alt="1 3" width="419" src="https://private-user-images.githubusercontent.com/121093383/384689504-5c042fa2-1edc-461e-9f3a-cdaae070f598.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNDMxNjMsIm5iZiI6MTczMTI0Mjg2MywicGF0aCI6Ii8xMjEwOTMzODMvMzg0Njg5NTA0LTVjMDQyZmEyLTFlZGMtNDYxZS05ZjNhLWNkYWFlMDcwZjU5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQxMjQ3NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yY2Y2NTRhMzA4MGY2YmNkMTVlNTBjZDUwYTdlNjg4MzEzY2RmMjc5MTVjODc4Zjk4YWYzY2VmMzI2YTU1NTVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JU6vD445USZ97EndKpz_7v4mv_CuKe9HRWWlG4GAmLw">

Transition doesn't take in a string:

![image](https://github.com/user-attachments/assets/9cfcf3cc-f30e-4745-98f0-78c76342612a)

Correct usage shown in the example snippet above.

**Comment by habibunnish** [comment]
i tried without string too but its didnt worked

**Comment by tjtanjin** [comment]
> i tried without string too but its didnt worked

In that case can you provide a minimal reproducible example on the [**playground**](https://react-chatbotify.com/playground) and paste it here?

**Comment by habibunnish** [comment]
i have added screenshot below
<img width="731" alt="3 1" src="https://github.com/user-attachments/assets/58af54a9-62f5-464f-bd36-b52116d66eac">
<img width="733" alt="3 2" src="https://github.com/user-attachments/assets/678de21d-7057-4317-bc63-ba047cb6e2d3">
<img width="578" alt="3 3" src="https://github.com/user-attachments/assets/58761a0c-77d4-49f2-bc73-664a86ccf94a">
<img width="569" alt="3 4" src="https://github.com/user-attachments/assets/f8cdbb72-8204-42ce-ac6b-a4575ff84f6f">
<img width="526" alt="3 5" src="https://github.com/user-attachments/assets/868eab97-468b-49bf-8158-cc6dbf24044a">

**Comment by tjtanjin** [comment]
@habibunnish Hmm is it possible to paste the code as it is? It's very hard to debug from long pieces of codes in screenshot (I can't search, can't copy etc) 😢

**Comment by habibunnish** [comment]
[index.zip](https://github.com/user-attachments/files/17691517/index.zip)

**Comment by habibunnish** [comment]
[index.zip](https://github.com/user-attachments/files/17691677/index.zip)
i have removed some imports as my project is not open source but now this file u can edit and run in local easily

**Comment by tjtanjin** [comment]
> [index.zip](https://github.com/user-attachments/files/17691677/index.zip) i have removed some imports as my project is not open source but now this file u can edit and run in local easily

Thanks! I'll take a look and get back to you.

**Comment by tjtanjin** [comment]
> [index.zip](https://github.com/user-attachments/files/17691677/index.zip) i have removed some imports as my project is not open source but now this file u can edit and run in local easily

Adding `transition` works on my side, what version of React ChatBotify are you on?

**Comment by tjtanjin** [comment]
> Iam using 2.0.0-beta.7 version. what version you are using ..??

Latest version is `beta.23`, try updating to it. Alternatively, use `transition: {duration: 0}` instead.

**Comment by habibunnish** [comment]
ok let me update it now and check it

**Comment by habibunnish** [comment]
thankyou @tjtanjin its working now

**Comment by tjtanjin** [comment]
> thankyou @tjtanjin its working now

No problem!
