### ISSUE TITLE
[Task] Update unit test for ChatHistoryService

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#268]
**Task Description:**
In React ChatBotify v2.0.0-beta.22, a new `storageType` was added to the chat history feature to support options for session storage. Previously, only local storage was supported. The unit test for ChatHistoryService thus needs to be updated to include tests for session storage as well.

**Deliverable(s):**
Updated unit test for ChatHistoryService that covers session storage option for `storageType`.

**Additional Context:**
The existing unit test can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/__tests__/services/ChatHistoryService.test.ts)

**Comment by mulla028** [comment]
Hello, @tjtanjin!
Are you still accepting the PRs for this issue? 
Please assign me!

**Comment by SDaniV** [comment]
Hello @tjtanjin, I raised a PR for this issue. I'll be happy to get a feedback. Please, let me know if there any changes that need to be made
