### ISSUE TITLE
[Task] Refactor chatinput component to support custom buttons

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#35]
**Description:**
Chatinput components currently support the following buttons that are pre-determined and can be configured to be shown or hidden:
- Voice Button
- Send Button

However, custom buttons are not allowed. It would be great to allow users to define their own button components for chatinput as well. Below I share a possible approach:
- Include a `buttons` prop in `chatinput` that takes in either a keyword (string) or a custom component (which would be buttons provided by the user)
- By default, `buttons` prop would look as such: `["voice", "send"]` (it essentially contains 2 keywords representing the default buttons)
- A user can specify a custom component within it so for example: `["voice", <CustomButton/>, "send"]`
- Buttons would be rendered in the order specified within the array

Feel free to take on a different approach if you have other ideas. Bear in mind that users need to be able to control the order of the buttons and that the configuration should be kept as simple as possible.

Related to #23

**Comment by Jason-35** [comment]
Hello, will be trying this task.

**Comment by tjtanjin** [comment]
Resolved by #45
