### ISSUE TITLE
[Bug] Fix chat history loading spinner height

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#43]
**Bug Description**
For chatbots configured to support chat history, you will notice a button at the top of the chat window that users can click to view historical messages. Upon clicking the button, the chat messages shift slightly as the loading spinner element that replaces the original button has a slightly different height. This does not cause issues functionally but is a small visual bug that would be nice fix.

**Steps To Reproduce**
Steps to reproduce the bug behavior:
1. Go to chatbot
2. Click on load chat history button
3. Notice existing messages shift slightly

**Expected behavior**
Existing messages should not even budge until the chat history is loaded

**Comment by mushroomgenie** [comment]
![ChatHistoryBug](https://github.com/tjtanjin/react-chatbotify/assets/24211855/fc5c78de-f885-4a7c-9d2e-50ba240ef289)

@tjtanjin Do you mean this budging of the existing message?

**Comment by tjtanjin** [comment]
@mushroomgenie I actually meant for slight shifting of messages vertically at the very moment when you click on the load chat history button. But now that you're pointing this out in the GIF above, fixing that would also be great!

**Comment by adel-gu** [comment]
Hi @mushroomgenie, @tjtanjin 👋🏼 

I wasn't able to replicate this behavior. Has it been fixed already?

**Comment by tjtanjin** [comment]
Hey @adel-gu, thanks for bringing this up! With the latest change to message containers in v2, this was unintentionally resolved 😝
