### ISSUE TITLE
[Task] Add integration test cases for sensitive text and markup language

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#59]
**Task Description:**
Currently, we run a suite of integration tests using cypress which can be found [**here**](https://github.com/tjtanjin/react-chatbotify/tree/main/cypress).

However, the test cases do not cover the [sensitive input](https://react-chatbotify.com/docs/api/settings#sensitiveinput) feature.

**Deliverable(s):**
New integration test cases that cover the testing of sensitive input.

**Additional Context:**
A possible approach is to add a new `block` to the existing flow in `App.tsx` that has `isSensitive` set to `true`. Then, check that user input in textarea is masked and when message is sent, chat bubble should also be masked.

Similar approach can be referenced here: https://github.com/tjtanjin/react-chatbotify/issues/29

**Comment by arulk8** [comment]
Hi @tjtanjin, I would like to work on it, I am able to understand sensitive text one. Not able to get what markup language mean here can you provide some reference!

**Comment by tjtanjin** [comment]
> Hi @tjtanjin, I would like to work on it, I am able to understand sensitive text one. Not able to get what markup language mean here. can you provide some reference ?

Hey @arulk8! Go ahead and take on this task for sensitive text input 😊

For the markup language, you can reference [this example](https://react-chatbotify.com/docs/examples/markup_message). Basically, the chatbot has markup language disabled by default so tags such as `<b>hello</b>` will be rendered as plaintext string. If enabled, it will show as **hello** instead.

**Comment by arulk8** [comment]
> > Hi @tjtanjin, I would like to work on it, I am able to understand sensitive text one. Not able to get what markup language mean here. can you provide some reference ?
> 
> Hey @arulk8! Go ahead and take on this task for sensitive text input 😊
> 
> For the markup language, you can reference [this example](https://react-chatbotify.com/docs/examples/markup_message). Basically, the chatbot has markup language disabled by default so tags such as `<b>hello</b>` will be rendered as plaintext string. If enabled, it will show as **hello** instead.

Got it!

**Comment by arulk8** [comment]
Hi @tjtanjin, I have raised PR for the same https://github.com/tjtanjin/react-chatbotify/pull/143
Please review.

**Comment by tjtanjin** [comment]
Completed with #143
