### ISSUE TITLE
[Bug] duplicate first message when chat history is disabled

### ISSUE THREAD

**Issue by nellysbr** [tjtanjin/react-chatbotify#63]
**Bug Description**

When i disable ChatHistory using *disabled* option, the first message comes duplicated.

**Steps To Reproduce**
Steps to reproduce the bug behavior:

```javascript

   chatHistory: {
          disabled: true,
    },
```

**Expected behavior**
Duplicated first message

**Screenshots**
![image](https://github.com/tjtanjin/react-chatbotify/assets/73605907/14363237-31ae-4d8b-a010-2afd7f47400a)

**Desktop (please complete the following information):**
 - OS: Linux 
 - Browser: Chrome, FIrefox

**Comment by tjtanjin** [comment]
Hey @nellysbr, I'm trying to reproduce this on the playground with no success, could you try reproducing it there and then sending me the `options`? On a side note, could this be relevant? [Khunshan Shahid](https://react-chatbotify.tjtanjin.com/docs/introduction/faq#q1-why-i-am-seeing-duplicate-messages-on-starting-the-chatbot)

**Comment by tjtanjin** [comment]
Hey @nellysbr, I'm trying to reproduce this on the playground with no success, could you try reproducing it there and then sending me the options? On a side note, could this [FAQ](https://react-chatbotify.tjtanjin.com/docs/introduction/faq#q1-why-i-am-seeing-duplicate-messages-on-starting-the-chatbot) be relevant?

**Comment by nellysbr** [comment]
Hey @tjtanjin ! Sure! 

```javascript

options={{
                tooltip: {
                  text: 'Precisa de ajuda?',
                },
                chatHistory: {
                  disabled: true,
                },
                botBubbleStyle: {
                  backgroundColor: '#f4f4f4',
                  color: '#444444',
                },
                footer: {
                  text: (
                    <>
                      <p>
                        <Link
                          href={'https://suave.ppg.br'}
                          className="font-bold text-black"
                          target="_blank"
                          title="Suave Comunicação e Marketing"
                        >
                          Suave Comunicação & Marketing
                        </Link>
                      </p>
                    </>
                  ),
                },
                fileAttachment: {
                  disabled: true,
                },
                emoji: {
                  disabled: true,
                },
                notification: {
                  disabled: true,
                },
                header: {
                  showAvatar: true,
                  avatar: '/assets/images/avatar-audi.webp',
                  title: (
                    <p className="font-bold pt-1">
                      Érica <br />
                      <span className="font-normal text-sm">
                        Assistente Audi Ribeirão Preto
                      </span>
                    </p>
                  ),
                },
                chatButton: {
                  icon: '/assets/images/avatar-audi.webp',
                },
                chatInput: {
                  enabledPlaceholderText: 'Digite aqui suas respostas',
                },
                theme: {
                  primaryColor: '#8e8e8e',
                  secondaryColor: '#444444',
                  fontFamily: 'Roboto',
                },
                headerStyle: {
                  background: '#000',
                  borderBottom: '6px solid #dc133e',
                  maxHeight: '100px',
                  alignItems: 'center',
                  justifyContent: 'space between',
                  padding: '20px 20px',
                  fontFamily: 'Roboto',
                },
}}


```

**Comment by nellysbr** [comment]
hey @tjtanjin ! Thank's for your reply! 

You can close this ticket! Ill create a new public repo (using next) to trying to reproduce the error for you so i can send it to you later! 

Thanks for your help!

**Comment by MrCordeiro** [comment]
Hi @tjtanjin !
I was able to replicate this issue. It happens when you use `React.StrictMode`. This makes React render twice in development mode to make sure that there are no side effects. I found this answer, while debugging my own application, helpful

https://stackoverflow.com/a/72238236/2533340

Cheers and thanks for your work with this awesome library! 💖

**Comment by tjtanjin** [comment]
Hey @MrCordeiro! Thank you for checking 😊 Your situation would match the scenario described in the [FAQ](https://react-chatbotify.tjtanjin.com/docs/introduction/faq#q1-why-i-am-seeing-duplicate-messages-on-starting-the-chatbot). Hoping that @nellysbr isn't having the same issue but for a different reason in NextJS because that would mean more digging required 😰
