### ISSUE TITLE
[Task] Add support for input validation within input textarea

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify#69]
**Description:**
Several users have brought up request for feature of allowing input validation to be done within the input textarea. Currently, the only way to do validation is after user sends the message. It would be great if validation can be done before a user even sends it. The tentative suggested approach is as follows:
- Add a new `inputValidator` attribute to `block` which accepts 2 properties `validator` and `errorMessage`
- The `validator` property will return `true` or `false` and if `false`, then the `errorMessage` is displayed

Position of the error message is tentatively above chat input container in the form of a small popup bar. The chat input textarea itself should also be outlined in red when error is shown. Upon displaying the error, it should only be dismissed when user make changes to the textarea.

**Comment by ehsanullahhaidary** [comment]
Hello @tjtanjin would you please assign me to this issue I am interested to contribute
I liked your repo a friend sent me your Reddit message
thanks

**Comment by ehsanullahhaidary** [comment]
Hello @tjtanjin would you please assign me to this issue I am interested to contribute
I liked your repo a friend sent me your Reddit message
thanks

**Comment by tjtanjin** [comment]
Hey @ehsanullahhaidary, thank you for the interest! I'm actually working on this issue personally as it is likely to be delivered as part of the plugin feature. Apologies that this is one of the issues where it's a little hard to have others help with 😅 There are a few other good-first-issues sitting around so feel free to take a look (or even suggest/create new issues) 😊!

**Comment by ehsanullahhaidary** [comment]
oops 😄 sorry to interrupted you task 
Ok I will check other issues as well
thanks for the nice reply 😃

**Comment by tjtanjin** [comment]
> oops 😄 sorry to interrupted you task 
> 
> Ok I will check other issues as well
> 
> thanks for the nice reply 😃

No worries, thank you for reaching out 😊

**Comment by tjtanjin** [comment]
Completed with the release of the [**Input Validator**](https://www.npmjs.com/package/@rcb-plugins/input-validator) plugin 😊
