### ISSUE TITLE
[Bug] Enabling "useCustomBotOptions: true" breaks chatbot

### ISSUE THREAD

**Issue by audols** [tjtanjin/react-chatbotify#74]
**Bug Description**
I am trying to set up my chatbot so that it is minimized by default, but when an external button is clicked, (a) a new message is appended (coming from an API call) and (b) the chatbot is toggled to Open. For the first part, I was successfully able to enable `useCustomMessages: true` and do some custom wiring to achieve this. For the second part, however, it seems like even setting `useCustomBotOptions: true` (with the intention of propagating `isOpen: true` downwards) breaks the UI.

Before setting `useCustomBotOptions: true`:
<img width="403" alt="image" src="https://github.com/tjtanjin/react-chatbotify/assets/7215101/1d1e369f-8ea9-4ee3-94fc-6b4b7e2c02d4">

After setting `useCustomBotOptions: true`: (no longer even clickable)
<img width="312" alt="image" src="https://github.com/tjtanjin/react-chatbotify/assets/7215101/4a3e307d-7fc8-4222-905a-e99b4508e8aa">

This behavior seems to persist even when:
* Adding `const defaultBotOptions = getDefaultBotOptions();` and using the spread operator to set the defaultBotOptions across every attribute of the `options` object
* Setting `useCustomMessages` to `false`

No build errors are reported, nor are any errors logged to console.

**Steps To Reproduce**
Steps to reproduce the bug behavior:
1. Within the `options` declaration, set `useCustomMessages: true`.
2. Previously working chatbot grays out and becomes unclickable. 

**Expected behavior**
Chatbot should continue to work.

**Screenshots**
See above.

**Desktop (please complete the following information):**
 - OS: MacOS 13.6.7
 - Browser: Chrome 126.0.6478.127

**Additional context**
Tried setting my `options` to only have `useCustomBotOptions: true` changed from the default to the same effect:
```
const defaultBotOptions = getDefaultBotOptions();
const [options, setOptions] = useState<Options>({
        ...defaultBotOptions,
        advance: {
            ...defaultBotOptions.advance,
            useCustomBotOptions: true,
        },
    });
```

**Comment by tjtanjin** [comment]
Hey @audols, can I check if apart from specifying `useCustomBotOptions: true`, you have also wrapped `<ChatBot/>` with a `BotOptionsContext.Provider` such as shown below?
```
<BotOptionsContext.Provider value={{botOptions: botOptions, setBotOptions: setBotOptions}}>
    <ChatBot options={botOptions} flow={flow}/>
</BotOptionsContext.Provider>
```
This is similar to what's done here which serves as a good reference: https://react-chatbotify.tjtanjin.com/docs/examples/custom_options

**Comment by audols** [comment]
Thanks @tjtanjin for the quick response - that seemed to do the trick. I'd glazed over the `<MessagesContext.Provider>` wrapper and assumed it applied to the other advanced use cases. This issue can be closed.
