### ISSUE TITLE
[Help] Problem installing React Chatbotify

### ISSUE THREAD

**Issue by miguelisidoro** [tjtanjin/react-chatbotify#79]
Hello,

I am having some trouble testing one of your demos.
The error is the following:

![image](https://github.com/tjtanjin/react-chatbotify/assets/5429152/030ee8b7-606a-4168-978e-403d2c27f3f8)

![image](https://github.com/tjtanjin/react-chatbotify/assets/5429152/8a91a560-4881-46a9-8c6e-0544e9326923)

The Css file is in the folder.

![image](https://github.com/tjtanjin/react-chatbotify/assets/5429152/5e45d1c6-9eef-4de3-8811-284dabaed339)

I tried using npm and pnpm and both give error. The commands I ran were:

npm install react-chatbotify
pnpm install react-chatbotify

In our React app, the import is:

import ChatBot from 'react-chatbotify';

Thanks

**Comment by tjtanjin** [comment]
From what I can gather, the error you're facing seems to occur during the SSR process where Vite does not know how to handle the CSS file. That said, adding the following to your vite config should resolve the issue:
```
ssr: {noExternal: [ /\.css$/, /^react-chatbotify/ ]},
```

Note that once the above issue is resolved, you'll likely need this FAQ since you're using Remix: https://react-chatbotify.tjtanjin.com/docs/introduction/faq#q8-i-am-using-nextjs-and-running-into-referenceerror-window-is-not-defined-errors-how-can-i-fix-this

I'll update the documentation FAQ to include Remix as well. Thanks!

**Comment by miguelisidoro** [comment]
Hello @tjtanjin ,

Thanks for reply, I already configured ssr in my vite.config.ts.
Now, I am getting:

![image](https://github.com/tjtanjin/react-chatbotify/assets/5429152/ccd4d1a1-0045-4897-af14-176853010179)

Our components are SSR and probably, you are expecting this to be client side rendered.
What change can I make here to ensure that the component is client side rendered?

Thanks

**Comment by tjtanjin** [comment]
> Hello @tjtanjin ,
> 
> Thanks for reply, I already configured ssr in my vite.config.ts. Now, I am getting:
> 
> ![image](https://private-user-images.githubusercontent.com/5429152/346875548-ccd4d1a1-0045-4897-af14-176853010179.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MTQ2NjcsIm5iZiI6MTcyMDUxNDM2NywicGF0aCI6Ii81NDI5MTUyLzM0Njg3NTU0OC1jY2Q0ZDFhMS0wMDQ1LTQ4OTctYWYxNC0xNzY4NTMwMTAxNzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDlUMDgzOTI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDA0ZmU2YWUzMzg0YjNhOTVkMGVkNzlmZjNiOWY3YTYyOTljYTMyYmQ2MmJmNmE3MzJmNDBjOWUyODUzYmE3ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vYkii_dQ9NVlonFpLizZpbpJotqC1XDlFxOXpDnvSWg)
> 
> Our components are SSR and probably, you are expecting this to be client side rendered. What change can I make here to ensure that the component is client side rendered?
> 
> Thanks

Read the second part of my previous reply again 😛

**Comment by miguelisidoro** [comment]
Hello @tjtanjin,

Thanks, it solved the problem, I can't see the chat bot yet but that is in my end now.
Please keep this open until I get this to work.

Thanks

**Comment by tjtanjin** [comment]
> Hello @tjtanjin,
> 
> Thanks, it solved the problem, I can't see the chat bot yet but that is in my end now. Please keep this open until I get this to work.
> 
> Thanks

No problem, let me know if you still need help!

**Comment by miguelisidoro** [comment]
Hello @tjtanjin,

I was able to incorporate React Chatbotify in our solution.

![image](https://github.com/user-attachments/assets/6d2c3ba6-8f7e-4463-82ef-dcae0ebac63b)

I have a few questions regaring customization:

1. Is it possible to remove the "Talk to me" part? If yes, how?
2. Is it possible to remove the message count part (the red zero at the begging of the chat)? If yes, how?
3. How can we change this image?

![image](https://github.com/user-attachments/assets/6c75d73f-3b13-490e-919a-ddb39883d51d)

4. Is it possible for the chat when maximized to occupy the whole screen in mobile devices?
5. How can we change the chat title from "Tan Jin" to another title?
6. How can we change the icon of the chat?

![image](https://github.com/user-attachments/assets/cf7df5a1-bb16-41b3-af62-0511d2122e9b)

7. How can we remove the "Powered by..." when the chatbot is maximized?

Thanks

**Comment by tjtanjin** [comment]
Hey @miguelisidoro, most of the answers can be found on the documentation website [here](https://react-chatbotify.tjtanjin.com/docs/api/bot_options). For ease of your reference, here are the links to each of your bullet points:

1) Refer to [tooltip](https://react-chatbotify.tjtanjin.com/docs/api/bot_options#tooltip)
2) Refer to [notification](https://react-chatbotify.tjtanjin.com/docs/api/bot_options#notification)
3) Refer to [chatbutton[(https://react-chatbotify.tjtanjin.com/docs/api/bot_options#chatbutton) and [chatbuttonstyle](https://react-chatbotify.tjtanjin.com/docs/api/bot_options#chatbutton)
4) Currently, the default behavior already maximizes the chatbot when opened on mobile
5) Refer to [header](https://react-chatbotify.tjtanjin.com/docs/api/bot_options#header)
6) Refer to [header](https://react-chatbotify.tjtanjin.com/docs/api/bot_options#header)
7) Refer to [footer](https://react-chatbotify.tjtanjin.com/docs/api/bot_options#footer)
8) I'm not familiar with Remix, but [action](https://remix.run/docs/en/main/route/action)/[loader](https://remix.run/docs/en/main/guides/data-loading) seems to be what you should look at
9) To get the user input within `getResponse`, you'll need to use `params.userInput` which is documented [here](https://react-chatbotify.tjtanjin.com/docs/api/params) and used repeated in this [example](https://react-chatbotify.tjtanjin.com/docs/examples/basic_form)

Strongly recommend to use the search function and live examples on the documentation website as well, but feel free to reach out if you need more assistance 😊

**Comment by tjtanjin** [comment]
> Hi @tjtanjin,
> 
> Thanks a lot, 8) and 9) are already working. About the others, I will take a look next week.
> 
> Have a nice weekend!
> 
> Thanks

No problem, feel free to close this issue once you've got the others sorted out 😊

**Comment by miguelisidoro** [comment]
Hello @tjtanjin, 

How can we write a response to the chat interface?

My code is:

const flow = {
		start: {
			message: 'Hello! How can I help you today?',
			path: 'loop'
		},
		loop: {
			message: async (params: any) => {
				const result = await getResponse(params.userInput);
				return result;
			},
			path: 'loop',
		}
	};

return (
    <>
    {isLoaded && (
      <Suspense fallback={<div>Loading...</div>}>
       <ChatBot options={{theme: {embedded: false}, chatHistory: {storageKey: 'example_smart_conversation'}}} flow={flow}/>
      </Suspense>
    )}
    </>
  );

Thanks

**Comment by tjtanjin** [comment]
Hey @miguelisidoro! Could you clarify what you're trying to do? Based on your flow the responses should already be appearing in the chat window (you can do a quick test on the playground as well)

**Comment by miguelisidoro** [comment]
Hello @tjtanjin ,

You are right, I already accomplished to show a response coming from our API that is already being displayed in the chat window.

Thanks

**Comment by miguelisidoro** [comment]
Hello @tjtanjin,

I am getting the following message. 

![image](https://github.com/user-attachments/assets/978fedfb-2b95-4363-bb83-9e1b4d49629b)

The hyperlinks are rendered as text, not as HTML. 
How can I render the response as HTML?

Thanks

**Comment by tjtanjin** [comment]
> Hello @tjtanjin,
> 
> I am getting the following message from our API.
> 
> ![image](https://private-user-images.githubusercontent.com/5429152/349982115-978fedfb-2b95-4363-bb83-9e1b4d49629b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMTIwMjQsIm5iZiI6MTcyMTMxMTcyNCwicGF0aCI6Ii81NDI5MTUyLzM0OTk4MjExNS05NzhmZWRmYi0yYjk1LTQzNjMtYmI4My05ZTFiNGQ0OTYyOWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MThUMTQwODQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzVlNWRjYjMyY2RlZDQ0ZTMwZjg4Nzc4OTgzNDAwNTZmMDU1MjRmYjcxMzc0NWI3ZWM3N2NhMzdkY2RkMGNiNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0YYorO1IwSQEg4-2M_ESTvJ4D2M-paWzLgk8u4j4uuo)
> 
> The hyperlinks are rendered as text, not as HTML. How can I render the response as HTML?
> 
> Thanks

Hey, you can look under `botBubble` that has `dangerouslySetInnerHtml`: https://react-chatbotify.tjtanjin.com/docs/api/bot_options#botbubble

**Comment by miguelisidoro** [comment]
Hello @tjtanjin ,

Thanks that was it!

My chatbot component is declared like this:

`<ChatBot options={{theme: {embedded: false}, botBubble: {dangerouslySetInnerHtml: true}, chatHistory: {storageKey: 'ai-assistant-conversation'}}} flow={flow}/>`

Is there a way to access chat history (a collection of messages sent by the user and its responses? What is chatHistory property for?

Thanks

**Comment by tjtanjin** [comment]
> Hello @tjtanjin ,
> 
> Thanks that was it!
> 
> My chatbot component is declared like this:
> 
> `<ChatBot options={{theme: {embedded: false}, botBubble: {dangerouslySetInnerHtml: true}, chatHistory: {storageKey: 'ai-assistant-conversation'}}} flow={flow}/>`
> 
> Is there a way to access chat history (a collection of messages sent by the user and its responses? What is chatHistory property for?
> 
> Thanks

The storage key can be used to access the stringified chat history in `localStorage`. If you want to manipulate the chatbot messages directly in your app, you can also use custom messages: https://react-chatbotify.tjtanjin.com/docs/examples/custom_messages

**Comment by miguelisidoro** [comment]
Hello @tjtanjin , 

Thanks for the reply.

How can we change the background color of the call to action image?

![image](https://github.com/user-attachments/assets/1c647d72-836e-4757-a7d7-9b9eb0c63d2f)

and how can we change the background color of the user message and the response?

![image](https://github.com/user-attachments/assets/342dcb7e-bfd9-4962-9237-3ef87ed6e95a)



Thanks

**Comment by tjtanjin** [comment]
Hey @miguelisidoro! Those are all available in the bot options page: https://react-chatbotify.tjtanjin.com/docs/api/bot_options

In particular, you can look at the styles section for all the available props to modify the appearance of the chatbot.

**Comment by miguelisidoro** [comment]
Hello @tjtanjin ,

Thanks for the quick response.

About the user interface, we were thinking in something like this:

![image](https://github.com/user-attachments/assets/40aff6b7-0f6d-42f1-b5e7-f313ff517aa8)

Is it possible to add a logo to the bot response, on the left of the response text? If yes, how?

Thanks

**Comment by tjtanjin** [comment]
Hey @miguelisidoro! It's possible to adjust the avatar for the bot messages within `botBubble`. You'll find `avatar` and `showAvatar` in there.

**Comment by miguelisidoro** [comment]
Thanks, I will give it a try!

**Comment by tjtanjin** [comment]
Hi @miguelisidoro, great to hear that! Unfortunately there's no such configuration, though that would certainly be useful to have. Perhaps you can make a suggestion for such a feature with more details?

**Comment by miguelisidoro** [comment]
Hello @tjtanjin,

[Done.](https://github.com/tjtanjin/react-chatbotify/issues/82) 

Thanks

**Comment by tjtanjin** [comment]
Great! Should this current issue be considered resolved?

**Comment by miguelisidoro** [comment]
Yes. If any other issue arises, I will open a new issue.

Thanks once again!
