### ISSUE TITLE
Site not working

### ISSUE THREAD

**Issue by clluiz** [tjtanjin/react-chatbotify#81]
The project website is not working: https://react-chatbotify.tjtanjin.com/. It takes a long time and ends up returning a timeout.

**Comment by tjtanjin** [comment]
Hey @clluiz, the site seems to be working currently, was it a temporary issue? If not could you try different networks/browsers?

That said the whole documentation website is also open source so if you are tight for time and need the docs urgently you can clone and run a local version: https://github.com/tjtanjin/react-chatbotify-docs

**Comment by clluiz** [comment]
Hi. It looks like it was a temporary issue.
