### ISSUE TITLE
[Feat] Chat Analytics

### ISSUE THREAD

**Issue by miguelisidoro** [tjtanjin/react-chatbotify#82]
Hello,

it would be nice to important to have chat analytics on the chat bot, namely a way to have some of the metrics contained [in this article](https://www.unitygroup.com/blog/chatbot-analytics-vital-bot-metrics-to-determine-success/).

Some of the things I personally find useful:

- User # number of requests
- User question and responses (configurable, for example, the first X questions and answers so that we can analise user chatbot interaction)

The implementation of where to store the chat analytics could be a configurable choice between:

- Azure Application Insights
- Google Tag Manager
- Any other that you can find useful

Thanks

**Comment by tjtanjin** [comment]
This is definitely nice to have, but might be better supported via plugins when support for it is available. Will cater for such a use case!

**Comment by tjtanjin** [comment]
Hey @miguelisidoro, thought to update that it is now possible to do chat analytics by relying on events: https://react-chatbotify.com/docs/api/events

In particular, you might want to leverage on the following:
- https://react-chatbotify.com/docs/api/events#rcbpostinjectmessageevent
- https://react-chatbotify.com/docs/api/events#rcbstopstreammessageevent

It's possible to write a plugin for this but it is unlikely that such a plugin will be done soon 🥹
