### ISSUE TITLE
after first response from api chatbotify input field becoming disabled

### ISSUE THREAD

**Issue by ajaysingh7623** [tjtanjin/react-chatbotify#84]
import axios from "axios";
import { React } from "react";
import ChatBot from "react-chatbotify";

const ChatBotify = () => {
  async function run(params) {
    const authToken = localStorage.getItem("authToken");
    const payload = {
      userinput: params.userInput,
      history: { quote: "14235436" }
    };
    const url = "urls";
    const config = {
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${authToken}`
      }
    };
    try {
      const response = await axios.post(url, payload, config);

      if (response.data) {
        params.streamMessage(response.data.bot_response);
      } else {
        console.error("Unexpected response structure:", response);
        return "Unexpected response from server.";
      }
    } catch (error) {
      console.error("Error during Axios request:", error);
      return "An error occurred while processing your request.";
    }
  }

  const flow = {
    start: {
      message: "Hello, I am  ChatBot, How Can I Help You!",
      path: "model_loop"
    },
    model_loop: {
      message: async (params) => {
        await run(params);
      },
      //   chatDisabled: false,
      path: "model_loop"
    }
  };

  const themes = [
    // { id: "solid_purple_haze", version: "0.1.0" },
    // { id: "minimal_midnight", version: "0.1.0" }
  ];

  return (
    <ChatBot
      //   themes={themes}
      settings={
        {
           audio: { disabled: false },
          
           voice: { disabled: false },
         
        }
      }
      flow={flow}
    />
  );
};
export default ChatBotify;
![gifdisabled](https://github.com/user-attachments/assets/b3af01f5-d716-4bdf-a248-89fe3301380a)

this is urgent if anyone got the clue plz tell

**Comment by ajaysingh7623** [comment]
@tjtanjin @team plz help me for this

**Comment by tjtanjin** [comment]
Hey @ajaysingh7623, I tried the following on the playground (you can copy and paste it there as well):
```
const MyChatBot = () => {
    async function run(params) {
        const authToken = localStorage.getItem("authToken");
        const payload = {
            userinput: params.userInput,
            history: {
                quote: "14235436"
            }
        };
        const url = "urls";
        const config = {
            headers: {}
        }
        try {
            const response = await fetch('https://jsonplaceholder.typicode.com/todos/1')

            if (response.data) {
                params.streamMessage(response.data.bot_response);
            } else {
                console.error("Unexpected response structure:", response);
                return "Unexpected response from server.";
            }
        } catch (error) {
            console.error("Error during Axios request:", error);
            return "An error occurred while processing your request.";
        }
    }
    let count = 0;
    const flow = {
        start: {
            message: "Hello, I am ChatBot, How Can I Help You!",
            path: "model_loop"
        },
        model_loop: {
            message: async (params) => {
                return await run(params);
            },
            // chatDisabled: false,
            path: "model_loop"
        }
    };
    return ( <
        ChatBot settings = {
            {
                general: {
                    embedded: true
                },
                chatHistory: {
                    storageKey: "example_smart_conversation"
                }
            }
        }
        flow = {
            flow
        }
        themes={[]} 
        />
    );
};

render( < MyChatBot / > )
```
This quite closely resembles what you have but I cannot reproduce the issue - can you verify your setup (with your urls) on the playground to see if you face it there as well? You can also reach out on [**discord**](https://discord.gg/6R4DK4G5Zh) if it's urgent - easier and faster to communicate there than via github issues.

**Comment by ajaysingh7623** [comment]
@tjtanjin now also it is not working for me. facing same issue

**Comment by tjtanjin** [comment]
@ajaysingh7623 Hmm that is very strange, the playground should be consistent for both of us. Could you take a similar video for the playground as you did for the earlier comment so that I can compare the visual discrepancies if any?

**Comment by ajaysingh7623** [comment]
@tjtanjin i am using  "react-chatbotify": "^2.0.0-beta.1", version. and browser google chrome and operating system windows 10

**Comment by tjtanjin** [comment]
You can bump up to beta.2, but I doubt that'll solve the issue. Issue with `.trim()` seems to suggest that within message processing, there's a certain piece of logic that expected a string but got something else. Can you check the bot response type and try removing `params.streamMessage` to return just a normal string to see if that's the issue?

**Comment by ajaysingh7623** [comment]
@tjtanjin 
![image](https://github.com/user-attachments/assets/2652f3a6-c197-40df-b8d5-409ced9f4f1d)
![image](https://github.com/user-attachments/assets/599d64bb-b31a-4309-b30f-18e546978947)
response.data.bot_response is string type only
but if i remove params.streamMessage it will through same error and did not return anything in chatbotify screen as i attach in screenshot same error also coming.

**Comment by tjtanjin** [comment]
@ajaysingh7623 Hmm let's try this incrementally and see where it starts to break:
1) Remove the function inside `message` and directly return a string instead.
2) If step 1 works, re-add the function but remove all current logic inside the function and just return a string.
3) If step 2 works, re-add the existing logic but mock the api response with a hard-coded string.
4) If step 3 works, run the existing code (this is where it currently breaks).

You can try the above and see at which step it starts to break.

**Comment by ajaysingh7623** [comment]
@tjtanjin thank you that problem is solved by removing async and await from run call.
i have one issue audio is not working.

**Comment by tjtanjin** [comment]
> @tjtanjin thank you that problem is solved by removing async and await from run call.
> 
> i have one issue audio is not working code is same

Hmm double check that audio is not disabled and it's toggled on. Also note that audio can only start playing after the user interacts with the page. There's also a live audio example that you can refer to on the documentation page.

**Comment by ajaysingh7623** [comment]
@tjtanjin  this is possible onlick of url in page it get redirected ?
![image](https://github.com/user-attachments/assets/ea1ec1fc-0bb8-4896-9ade-2bdd0ed2fe81)
Quote created D24TGYVF5-01, with transaction ID 40000045151, use this link to open the quote (https://cpq-itg.ext.hp.com/page/q/D24TGYVF5-01)

**Comment by tjtanjin** [comment]
> @tjtanjin  this is possible onlick of url in page it get redirected ?
> 
> ![image](https://github.com/user-attachments/assets/ea1ec1fc-0bb8-4896-9ade-2bdd0ed2fe81)
> 
> Quote created D24TGYVF5-01, with transaction ID 40000045151, use this link to open the quote (https://cpq-itg.ext.hp.com/page/q/D24TGYVF5-01)
> 
> 
> 
> 

Yup that's achievable via the `dangerouslySetInnerHtml` option under `botBubble` that allows you to have html within the chat messages. You're responsible for sanitizing the input though!

**Comment by ajaysingh7623** [comment]
> > @tjtanjin  this is possible onlick of url in page it get redirected ?
> > ![image](https://private-user-images.githubusercontent.com/33036454/352626288-ea1ec1fc-0bb8-4896-9ade-2bdd0ed2fe81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwMTg0ODUsIm5iZiI6MTcyMjAxODE4NSwicGF0aCI6Ii8zMzAzNjQ1NC8zNTI2MjYyODgtZWExZWMxZmMtMGJiOC00ODk2LTlhZGUtMmJkZDBlZDJmZTgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDE4MjMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxZDQzODVhYmZiNGI4OWViOWE5NGU5ZTI3ZDQzNTZlOTgyMDI2MGQ3MzY5ODJjY2I1ODA0ZjA3YmEwYTg2YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bgcclzr0E_1i1tQtUiesW0_Orx44mM1vGDrz5D1-ov8)
> > Quote created D24TGYVF5-01, with transaction ID 40000045151, use this link to open the quote (https://cpq-itg.ext.hp.com/page/q/D24TGYVF5-01)
> 
> Yup that's achievable via the `dangerouslySetInnerHtml` option under `botBubble` that allows you to have html within the chat messages. You're responsible for sanitizing the input though!

can you please provide the example or page so, i can refer to it.

**Comment by tjtanjin** [comment]
@ajaysingh7623 

The `botBubble` properties can be found [**here**](https://react-chatbotify.com/docs/api/settings/#botbubble). There's also no `tapToPlay` property within `audio` so you can remove that (you may find the search bar at the top of the documentation useful for navigating around).

Does the [**audio example**](https://react-chatbotify.com/docs/examples/audio) work for you?

**Comment by ajaysingh7623** [comment]
> @ajaysingh7623
> 
> The `botBubble` properties can be found [**here**](https://react-chatbotify.com/docs/api/settings/#botbubble). There's also no `tapToPlay` property within `audio` so you can remove that (you may find the search bar at the top of the documentation useful for navigating around).
> 
> Does the [**audio example**](https://react-chatbotify.com/docs/examples/audio) work for you?

@tjtanjin i removed tapToPlay attribute then also not working

**Comment by ajaysingh7623** [comment]
> > > @tjtanjin  this is possible onlick of url in page it get redirected ?
> > > ![image](https://private-user-images.githubusercontent.com/33036454/352626288-ea1ec1fc-0bb8-4896-9ade-2bdd0ed2fe81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwMTg0ODUsIm5iZiI6MTcyMjAxODE4NSwicGF0aCI6Ii8zMzAzNjQ1NC8zNTI2MjYyODgtZWExZWMxZmMtMGJiOC00ODk2LTlhZGUtMmJkZDBlZDJmZTgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDE4MjMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxZDQzODVhYmZiNGI4OWViOWE5NGU5ZTI3ZDQzNTZlOTgyMDI2MGQ3MzY5ODJjY2I1ODA0ZjA3YmEwYTg2YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bgcclzr0E_1i1tQtUiesW0_Orx44mM1vGDrz5D1-ov8)
> > > Quote created D24TGYVF5-01, with transaction ID 40000045151, use this link to open the quote (https://cpq-itg.ext.hp.com/page/q/D24TGYVF5-01)
> > 
> > 
> > Yup that's achievable via the `dangerouslySetInnerHtml` option under `botBubble` that allows you to have html within the chat messages. You're responsible for sanitizing the input though!
> 
> @tjtanjin can you please provide the example or page so, i can refer to it.

but this will provide bold ,italic text 
not like href link so we can click in it and move to that page @tjtanjin

**Comment by tjtanjin** [comment]
> > > > @tjtanjin  this is possible onlick of url in page it get redirected ?
> > > > ![image](https://private-user-images.githubusercontent.com/33036454/352626288-ea1ec1fc-0bb8-4896-9ade-2bdd0ed2fe81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwMTg0ODUsIm5iZiI6MTcyMjAxODE4NSwicGF0aCI6Ii8zMzAzNjQ1NC8zNTI2MjYyODgtZWExZWMxZmMtMGJiOC00ODk2LTlhZGUtMmJkZDBlZDJmZTgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDE4MjMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxZDQzODVhYmZiNGI4OWViOWE5NGU5ZTI3ZDQzNTZlOTgyMDI2MGQ3MzY5ODJjY2I1ODA0ZjA3YmEwYTg2YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bgcclzr0E_1i1tQtUiesW0_Orx44mM1vGDrz5D1-ov8)
> > > > Quote created D24TGYVF5-01, with transaction ID 40000045151, use this link to open the quote (https://cpq-itg.ext.hp.com/page/q/D24TGYVF5-01)
> > > 
> > > 
> > > Yup that's achievable via the `dangerouslySetInnerHtml` option under `botBubble` that allows you to have html within the chat messages. You're responsible for sanitizing the input though!
> > 
> > 
> > @tjtanjin can you please provide the example or page so, i can refer to it.
> 
> but this will provide bold ,italic text not like href link so we can click in it and move to that page @tjtanjin

It also provides the anchor element `<a>` for you to make the link clickable. By default it's being treated as a string because the chatbot isn't making assumptions about the output desired.

**Comment by tjtanjin** [comment]
> > @ajaysingh7623
> > The `botBubble` properties can be found [**here**](https://react-chatbotify.com/docs/api/settings/#botbubble). There's also no `tapToPlay` property within `audio` so you can remove that (you may find the search bar at the top of the documentation useful for navigating around).
> > Does the [**audio example**](https://react-chatbotify.com/docs/examples/audio) work for you?
> 
> @tjtanjin i removed tapToPlay attribute then also not working

Is the audio example working for you on the documentation website?

**Comment by ajaysingh7623** [comment]
> > > @ajaysingh7623
> > > The `botBubble` properties can be found [**here**](https://react-chatbotify.com/docs/api/settings/#botbubble). There's also no `tapToPlay` property within `audio` so you can remove that (you may find the search bar at the top of the documentation useful for navigating around).
> > > Does the [**audio example**](https://react-chatbotify.com/docs/examples/audio) work for you?
> > 
> > 
> > @tjtanjin i removed tapToPlay attribute then also not working
> 
> Is the audio example working for you on the documentation website?

yes it is working in documentation
but same thing i used in my code it is not working
![image](https://github.com/user-attachments/assets/0f467014-4768-4490-aca9-782bb8c96713)

**Comment by tjtanjin** [comment]
@ajaysingh7623 As a sanity check have you checked local audio and have you tried a different device or browser? If the documentation website example is working then there's a good chance that it's a local issue.

**Comment by ajaysingh7623** [comment]
Thank you @tjtanjin for :-after first response from api chatbotify input field becoming disabled
