### ISSUE TITLE
how to change chatbotify icon and size

### ISSUE THREAD

**Issue by ajaysingh7623** [tjtanjin/react-chatbotify#86]
![image](https://github.com/user-attachments/assets/d63635ef-bb73-4877-83b0-ddbaca35b71b)
here i am attaching the screenshot highlighting in yellow.
@tjtanjin please help me for this.

**Comment by tjtanjin** [comment]
Hey @ajaysingh7623, you can look over [**here**](https://react-chatbotify.com/docs/api/settings#chatbutton) for the icon and look under chatButtonStyle [**here**](https://react-chatbotify.com/docs/api/styles) for styling it.

**Comment by ajaysingh7623** [comment]
![image](https://github.com/user-attachments/assets/0ecede0d-8a0c-4edd-bc12-3b4aaaf907d1)
here i use chatbutton inside setting but this is not reflecting changes
@tjtanjin

**Comment by tjtanjin** [comment]
@ajaysingh7623 It's `chatButton`, not `ChatButton`

**Comment by ajaysingh7623** [comment]
@tjtanjin thank you now it is working.
