### ISSUE TITLE
audio not working

### ISSUE THREAD

**Issue by ajaysingh7623** [tjtanjin/react-chatbotify#87]
![image](https://github.com/user-attachments/assets/2ec47006-deeb-4b89-bbf7-dff82829812d)
![image](https://github.com/user-attachments/assets/bdcaf21b-ef5a-49e3-906a-675914202e06)
here i attached the screenshot and the error i am getting in browser
plz help on this @tjtanjin

**Comment by tjtanjin** [comment]
@ajaysingh7623 That message is saying the user needs to interact with the page before audio can be played.

**Comment by ajaysingh7623** [comment]
import axios from "axios";
import { CDN_LOTTIES } from "config/env";
import React, { useState } from "react";
import ChatBot from "react-chatbotify";
import { useDispatch } from "react-redux";
function ChatBotify() {
  const dispatch = useDispatch();
  const [quote, setQuote] = useState("");
  // Select the session history from the Redux store
  //   const {quote,quoteID} = useSelector((state) => state.chatBotifyReducer);
  console.log(quote, "session");

  //   const [sessionHistory, setSessionHistory] = useState({
  //     quote: "",
  //     quoteID: ""
  //   });
  //   console.log(sessionHistory, "hh");
  async function run(params) {
    const authToken = localStorage.getItem("authToken");
    const payload = {
      userinput: params?.userInput,
      history: {
        quote: "14235436",
        quoteID: quote ||""
      }
    };
    const url = "/api/start";
    const config = {
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${authToken}`
      }
    };
    try {
      const response = await axios.post(url, payload, config);
      const quote = response?.data?.session_history.quote;
        const quoteID = response?.data?.session_history.quoteID;
      setQuote(quoteID);
      //   setSessionHistory((prev) => ({
      //     ...prev,
      //     quote: quote,
      //     quoteID: quoteID
      //   }));
      // dispatch({
      //   type: "SET_SESSION_HISTORY",
      //   payload: response?.data?.session_history
      // });
      if (response.data) {
        params.streamMessage(
          response?.data?.bot_response +
            " " +
            response?.data?.next_step_recommendation
        );
      } else {
        console.error("Unexpected response structure:", response);
        return "Unexpected response from server.";
      }
    } catch (error) {
      console.error("Error during Axios request:", error);
      return "An error occurred while processing your request.";
    }
  }
  const flow = {
    start: {
      message: "Hello, I am CPQ ChatBot, How Can I Help You!",
      path: "model_loop"
    },
    model_loop: {
      message: (params) => {
        run(params);
      },
      path: "model_loop"
    }
  };

  const themes = [
    { id: "minimal_midnight", version: "0.1.0" }
  ];
  const microsoftLogo = `${CDN_LOTTIES.replace(
    "lotties",
    "images"
  )}microsoft-edge.png`;
  const styles = {
    // chatButtonStyle: {
    //   height: "10%",
    //   width: "10%"
    // }
  };

  return (
    <ChatBot
      themes={themes}
      styles={styles}
      settings={{
        audio: { disabled: false, defaultToggledOn: false },
        voice: { disabled: false },
        chatHistory: { storageKey: "example_audio" },
        chatButton: {
          icon: microsoftLogo
        }
      }}
      flow={flow}
    />
  );
}
export default ChatBotify;
can u plz go through the code something i am missing so audio is not working

**Comment by tjtanjin** [comment]
> ![image](https://private-user-images.githubusercontent.com/33036454/352714818-2ec47006-deeb-4b89-bbf7-dff82829812d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwOTYwNjksIm5iZiI6MTcyMjA5NTc2OSwicGF0aCI6Ii8zMzAzNjQ1NC8zNTI3MTQ4MTgtMmVjNDcwMDYtZGVlYi00Yjg5LWJiZjctZGZmODI4Mjk4MTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDE1NTYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2NjRjOTBmZmU1MTc4YjYzOGUzOTE0ZGRjNzBkNWYyYTdhYWU3ZWI0ZDA0MmQ1YTZlMjRhNjFhMDEwMzg0MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CY4k6d1x87nxVRbZmuWf4Prwx4HxF5JAr3dpns20nmc) ![image](https://private-user-images.githubusercontent.com/33036454/352714841-bdcaf21b-ef5a-49e3-906a-675914202e06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwOTYwNjksIm5iZiI6MTcyMjA5NTc2OSwicGF0aCI6Ii8zMzAzNjQ1NC8zNTI3MTQ4NDEtYmRjYWYyMWItZWY1YS00OWUzLTkwNmEtNjc1OTE0MjAyZTA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDE1NTYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzYzI5MTE0N2FhZDMxNTAwNjE0NGIzM2YwOTIwZjViNjA2MmQ2MTQxOWYxNDhjMTM5MjAyYzA4NjA5MWQ4YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5UbBS073wNwadEt1aqivLCE-tnrKoeBBWXJloIBhwxI) here i attached the screenshot and the error i am getting in browser plz help on this @tjtanjin

Based on the message in the yellow box above, the chatbot was already trying to play audio (i.e. audio is working) but was unable to, because the user has yet to interact with the page. Try clicking around and then trigger the next message.

**Comment by ajaysingh7623** [comment]
> > ![image](https://private-user-images.githubusercontent.com/33036454/352714818-2ec47006-deeb-4b89-bbf7-dff82829812d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwOTYwNjksIm5iZiI6MTcyMjA5NTc2OSwicGF0aCI6Ii8zMzAzNjQ1NC8zNTI3MTQ4MTgtMmVjNDcwMDYtZGVlYi00Yjg5LWJiZjctZGZmODI4Mjk4MTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDE1NTYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2NjRjOTBmZmU1MTc4YjYzOGUzOTE0ZGRjNzBkNWYyYTdhYWU3ZWI0ZDA0MmQ1YTZlMjRhNjFhMDEwMzg0MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CY4k6d1x87nxVRbZmuWf4Prwx4HxF5JAr3dpns20nmc) ![image](https://private-user-images.githubusercontent.com/33036454/352714841-bdcaf21b-ef5a-49e3-906a-675914202e06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwOTYwNjksIm5iZiI6MTcyMjA5NTc2OSwicGF0aCI6Ii8zMzAzNjQ1NC8zNTI3MTQ4NDEtYmRjYWYyMWItZWY1YS00OWUzLTkwNmEtNjc1OTE0MjAyZTA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDE1NTYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzYzI5MTE0N2FhZDMxNTAwNjE0NGIzM2YwOTIwZjViNjA2MmQ2MTQxOWYxNDhjMTM5MjAyYzA4NjA5MWQ4YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5UbBS073wNwadEt1aqivLCE-tnrKoeBBWXJloIBhwxI) here i attached the screenshot and the error i am getting in browser plz help on this @tjtanjin
> 
> Based on the message in the yellow box above, the chatbot was already trying to play audio (i.e. audio is working) but was unable to, because the user has yet to interact with the page. Try clicking around and then trigger the next message.

hello @tjtanjin  i tried this thing but then also it is happening

**Comment by tjtanjin** [comment]
The yellow box message appearing is indicative that it is trying to play an audio, but I can't really tell why you're not getting the sound (it seems likely it's a local issue since it works on the playground for you). Is your project available on GitHub? If so I could clone and take a look.

**Comment by ajaysingh7623** [comment]
> The yellow box message appearing is indicative that it is trying to play an audio, but I can't really tell why you're not getting the sound (it seems likely it's a local issue since it works on the playground for you). Is your project available on GitHub? If so I could clone and take a look.

no it is not in github
we can connect on google-meet if u don't mind?

**Comment by tjtanjin** [comment]
> > The yellow box message appearing is indicative that it is trying to play an audio, but I can't really tell why you're not getting the sound (it seems likely it's a local issue since it works on the playground for you). Is your project available on GitHub? If so I could clone and take a look.
> 
> no it is not in github we can connect on google-meet if u don't mind?

We can use discord if you're already in the server

**Comment by ajaysingh7623** [comment]
@tjtanjin Thank you now it is working
