### ISSUE TITLE
[Feat] Be able to change the "typing-indicator" dots style

### ISSUE THREAD

**Issue by pferioli** [tjtanjin/react-chatbotify#91]
I'm using a gray background so the dots are not visible.

![image](https://github.com/user-attachments/assets/e7c38123-c284-43d4-a4fc-a5569a5eef61)

Adding a style properties for the dots to change the color

declare a style for the folliwing style in `src/components/ChatBotBody/ChatBotBody.tsx`

```
.rcb-dot {
	width: 8px;
	height: 8px;
	border-radius: 50%;
	background-color: #ccc;
	margin-right: 4px;
	animation: rcb-typing 1s infinite;
}
```

**Comment by tjtanjin** [comment]
Hey @pferioli, I can explore adding a style prop for this. In the meantime you can directly target the css class you pointed out in the screenshot with your desired changes.

**Comment by tjtanjin** [comment]
Hey @pferioli, this has been added in `v2.0.0-beta.7`
