### ISSUE TITLE
React Native Support

### ISSUE THREAD

**Issue by markmadlangbayan** [tjtanjin/react-chatbotify#95]
Can this work with React Native?  Our product has both ReactJS and React-Native.

**Comment by tjtanjin** [comment]
Hey @markmadlangbayan! Unfortunately, the library doesn't support react native. It's something I hope to explore down the road but unlikely to be anytime soon 😔

**Comment by markmadlangbayan** [comment]
> Hey @markmadlangbayan! Unfortunately, the library doesn't support react native. It's something I hope to explore down the road but unlikely to be anytime soon 😔

Thank you for the quick reply @tjtanjin!
