### ISSUE TITLE
Change de style from principal button

### ISSUE THREAD

**Issue by dspwebstudiomx** [tjtanjin/react-chatbotify#96]

**Comment by tjtanjin** [comment]
Hey @dspwebstudiomx, could you elaborate more on this issue? 😅

**Comment by dspwebstudiomx** [comment]
![image](https://github.com/user-attachments/assets/4e2d15d2-219c-4599-821c-31044b72f815)
 I need to change the backgroundColor of this and add padding to view the logo more small

**Comment by tjtanjin** [comment]
Hey @dspwebstudiomx, you're probably looking at the `chatButtonStyle` and `tooltipStyle` which you can find here: https://react-chatbotify.com/docs/api/styles

**Comment by dspwebstudiomx** [comment]
No, I need to change de gradient backgroundcolor, with no color, and adapt my logo size.

**Comment by tjtanjin** [comment]
Hmm you can tinker with `primaryColor` and `secondaryColor`, or target the CSS classes directly. That said, buttons/icons in general have been rather inconsistent in the style props they provide. If you wait a couple days, I'll release an update with new style props that'll separate button styling from icon styling to make things more convenient.

**Comment by tjtanjin** [comment]
Hey @dspwebstudiomx, bump the library up to **v2.0.0-beta.5**, you'll then be able to use `chatButtonStyle` and `chatIconStyle` to achieve your desired modifications 😊

**Comment by tjtanjin** [comment]
Seeing as you have emoted I assume this is resolved :P Feel free to reach out if there're more issues again 😊
