### ISSUE TITLE
[Help] Base 64 Images not rendered in Azure web application

### ISSUE THREAD

**Issue by miguelisidoro** [tjtanjin/react-chatbotify#97]
Hello,

I have a web application deployed to Azure and as you can see the send button and the close button in the header are not shown. After inspecting html, I see that they are base64 encoded images and for some reason, they are not rendered.

![image](https://github.com/user-attachments/assets/e37d60a1-6e22-4506-93db-2f529094ace8)

Anyone knows why they are not rendered when deployed to Azure?

Thanks

**Comment by tjtanjin** [comment]
Hey @miguelisidoro, that might be something only Azure can answer 😅That said, you can try downloading the assets yourself, then including them via `settings`. That might just be a viable workaround.

**Comment by miguelisidoro** [comment]
Hello,

In which settings do I specify these two images (send and close images)?

Thanks

**Comment by miguelisidoro** [comment]
Thanks, I will try it out.

**Comment by miguelisidoro** [comment]
Done, it worked.

I added the images from a public blob storage and it works now :).

Thanks
